### ISSUE TITLE
Lockups upon DAG generation with AMD RX 5700XTs

### ISSUE THREAD

**Issue by wtu-fl** [nanopool/nanominer#101]
I have 2 rigs with identical Intel-based, PCIe 3.0 motherboards, running Windows 10.  Each rig has at least 4 identical AMD Navi GPUs.  They will run for days, then crash.  When trying to restart them from cold, it is tough to get past Nanominer's DAG Generation without locking up the rig.  Oddly, I can start ANY 3 of the GPUs with no problem, but getting 4 or more GPUs going at once is a problem.  When I have all the GPUs set at their peak performance with Afterburner, Nanominer's DAG generation happens on all GPUs at the same time and "Crash."  Perhaps too big a power surge all at once?  (1600watt PSU, but 4 GPUs going from 0 to max all at once is still a big surge).  I also learned by studying Device Manager, that on my motherboard, Even# GPUs are on Southbridge, and Odd# GPUs are on Northbridge.  My solution was to set each of the Even# GPUs to different Memory and Core clocks, with only one at the highest setting, the others lower and different.  Same among the Odd# GPUs, only one at the highest clock settings, the others lower and different.  That way, during DAG generation, the GPUs all take a slightly different amount of time to initialize.  Once I survive Nanominer DAG generation, I can bump the lower GPUs up in speed some.  So now I'm wondering if a new DAG Epoch means a new DAG generation in Nanominer, explaining my crashes every few days.  Whether it is a power surge or the inability of Southbridge or Northbridge to handle too much at the exact same millisecond, MY REQUEST IS THIS:  Can you add a small delay between each GPU on DAG Generation?  Then I would not have to babysit a restart of the rigs to get them going again. My workaround involves timing them so that they complete DAG Generation at least a few milliseconds apart, and it would be nice if you could do the same built-in to Nanominer.
This is sufficient difference in timing on my rigs:
GPU0: 3991 MB DAG generated in 5.21 seconds
GPU1: 3991 MB DAG generated in 5.28 seconds
GPU3: 3991 MB DAG generated in 5.32 seconds
GPU2: 3991 MB DAG generated in 5.35 seconds
When they were all closer than that in timing, it would crash upon initializing the fourth GPU, whichever one that happened to be.
If it's easier, how about DAG generation and start mining, but one GPU at a time, instead of all at the same time... we're only talking about 20 seconds here.  That is WAY faster than what it takes me to bring the rig up more slowly "the hard way."  Thanks!

**Comment by Grumpy-Dwarf** [comment]
Thanks, will add a feature for generating single DAG at a time, one-by-one.

**Comment by wtu-fl** [comment]
That would be Awesome.  Maybe you aren't as Grumpy as you think!  LOL

**Comment by Grumpy-Dwarf** [comment]
We now have working yet not documented `dagSer` option in version 3.0.0. Just add the following line to your config file:
```ini
dagSer=true
```
and DAG generation will be serialized.

**Comment by Grumpy-Dwarf** [comment]
Documented feature since version 3.0.1. Feel free to reopen the issue if serialized DAGs generation doesn't help.
