### ISSUE TITLE
Trojan:Win32/Wacatac.D3!ml

### ISSUE THREAD

**Issue by Shadowplays4k** [nanopool/nanominer#105]
Trojan:Win32/Wacatac.D3!ml

in service.dll

version 1.13.0

Type: Trojan, Password stealing virus, Banking malware, Spyware

**Comment by kristofias** [comment]
I confirm. Windows defender blocked it.

**Comment by crankfunk** [comment]
Cannot confirm. McAfee does not recognize a virus on service.dll. It just isolates the nanominer.exe – as it does with all cryptominers to protect from cryptojacking. I also uploaded my service.dll file to [VirusTotal](https://www.virustotal.com/gui/), which returns no positives at all.

Did you download your copy from a trusted source?

**Comment by wrkc** [comment]
Also nanominer is flagged as malicious by virustotal - https://www.virustotal.com/gui/file/ad5243ca479c511c90612e716ba2f665b7e39d9882a631f5ec4e0eea06e7f0ba/details
downloaded from github

**Comment by Grumpy-Dwarf** [comment]
AV usually try to protect users from cryptojacking.
This repo is the only trusted way to download nanominer. We hash sha256 checksums in every release to confirm file is fine.
