### ISSUE TITLE
Cannot find nvrtc64_111_0.dll after update to 1.13.1

### ISSUE THREAD

**Issue by markusbrovold** [nanopool/nanominer#106]
I solved it by renaming nvrtc64_100_0.dll to nvrtc64_111_0.dll, but dont know if this is optimal. At least it works.

**Comment by Grumpy-Dwarf** [comment]
Thanks for workaround. Will fix in next release.

**Comment by Grumpy-Dwarf** [comment]
Fixed in version 3.0.0.
