### ISSUE TITLE
1.13.1 breaks CPU mining

### ISSUE THREAD

**Issue by DarkVoyage** [nanopool/nanominer#107]
It just says now that it can't find GPUs and doesn't continue like before with same settings.
I understand that nothing changes and there's no need to update. But I use autoupdate.

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting, bug appeared in code related to future CUDA 11 release. Will fix.

**Comment by Grumpy-Dwarf** [comment]
Could you please share your config file for us to verify? You can remove your exact wallet from it, it does not matter.

**Comment by Grumpy-Dwarf** [comment]
This bug is probably fixed in 3.0.0 release.

**Comment by DarkVoyage** [comment]
Problem is not resolved in any of recent versions.

[RandomX]
coin = XMR
wallet = 
rigName = 
email = 
noLog = true

[RandomHash2]
coin = PASC
wallet = 
rigName = 
pool1 = fastpool.xyz:3337
pool2 = coinotron.com:3350
email = 
noLog = true

**Comment by Grumpy-Dwarf** [comment]
I see. This is the new behavior of our miner now due to new 30xx series GPUs support. If GPU algorithm was set up but there are no devices we stop because user probably has incompatible miner version and need to run `cuda11` miner version.
