### ISSUE TITLE
3.0.0 cuda11.1 problem

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [nanopool/nanominer#108]
Hi.
I have rig with GTX 1070 GPUs and new version 3.0.0 works only with cuda10 nanominer binary.
When trying to mining using binary cuda 11 (11.1 as I see), then got below errors:

020-11-16 16:59:14: System exception: 
2020-11-16 16:59:14: device: 1; CUDA_ERROR_INVALID_HANDLE
2020-11-16 16:59:14: System exception: 
2020-11-16 16:59:14: device: 4; CUDA_ERROR_INVALID_HANDLE
2020-11-16 16:59:14: GPU2: 2615 MB DAG generated in 12.71 seconds
2020-11-16 16:59:14: GPU5: 2615 MB DAG generated in 12.69 seconds
(...)
Raven - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 04:31

My machine is Linux Ubuntu 18 Linux
NVIDIA driver 455.28 - which is CUDA 11.1 compatible.

Other miners compiled for CUDA 11.1 are working OK on this rig.

Also both binary version works ok on other rig - with AMD RX 5700 on both tested: eth and kawpow algos.

**Comment by tymoteuszrogalewski** [comment]
Did some test and see that this error is only when mining RVN and only on yours cuda11.1 binary.

Other coins works ok on both cuda10 and 11 binaries.

**Comment by Grumpy-Dwarf** [comment]
I've checked Nvidia 1060 mining RVN with `cuda11` version on 455.32.00 and it worked. Maybe there are some driver-specific issues.
That's why we've released two packages for miner. `cuda11` version is for 30xx GPUs and most recent Nvidia drivers.

**Comment by Grumpy-Dwarf** [comment]
Guess this was driver-specific issue.
