### ISSUE TITLE
Update Error Cuda 11

### ISSUE THREAD

**Issue by jgonzi** [nanopool/nanominer#109]
Hi,

I have checked that if you have autoupdate on.. it will update to version CUDA 10 not to CUDA 11 if you have installed Version CUDA 11. 

I suppose you need to check you actual version before select the new update.

**Comment by Grumpy-Dwarf** [comment]
This was only fixed in latest `3.1.1` version. So `3.1.1-cuda` is supposed to update to `3.1.2-cuda` or `3.2.0-cuda`.

**Comment by Grumpy-Dwarf** [comment]
Just checked, nanominer 3.1.1-cuda11has successfully downloaded and run 3.1.2-cuda11 version.
