### ISSUE TITLE
Mining ETH

### ISSUE THREAD

**Issue by Lump01** [nanopool/nanominer#111]
I’ve been mining for 9ish hours, but no change to my wallet. I know I’m mining with not too much hashing power (only one fairly good GPU), but why hasn’t it updated in my wallet? How do I know it’s working?

**Comment by kontr0x** [comment]
I got the same problem. Is there any way I could lookup how much it mined?

**Comment by crankfunk** [comment]
You can see how much you alread mined if you enter your account address that you specified in your config here: https://eth.nanopool.org/ (put your address in the upper right corner). "9ish" hours is not very much in the minig world btw. It will probably not very much ETH, just some cents. There is a minimum payout threshold of 0.2 ETH, so the pool will hold your ETH until you reached that threshold.

**Comment by Lump01** [comment]
Awesome, thanks. That solved my problem.

Jonathan Lumpkin
