### ISSUE TITLE
Problem mining ETC GTX 1060 3g

### ISSUE THREAD

**Issue by aleksandar1205** [nanopool/nanominer#113]
Current DAG size for ETC is 2.5GB. The card is loading fine the DAG size. But there is a problem mining with it.
GTX 1060 3GB
See screenshot below
https://ibb.co/7RkdtcD
Any software problem? It mines with 2MH and it cannot load full potential.
Regards

**Comment by Grumpy-Dwarf** [comment]
Please try running it on Linux. Windows allocates additional data on GPU for itself. So DAG probably doesn't fit to GPU on Windows.
