### ISSUE TITLE
GPU 0 hung up. Try to decrease the "memTweak" parameter value for GPU 0

### ISSUE THREAD

**Issue by Skepix** [nanopool/nanominer#114]
New miner here, decided to try out mining on my 3070, I realized that the program restarts every 2 minutes or so and when I check logs this shows up
GPU 0 hung up. Try to decrease the "memTweak" parameter value for GPU 0

I'm lost, any help is appreciated!

**Comment by severusnt** [comment]
Hello. Did u solve it? My card worked today, but when i was at work it start selfrestarting with same error in logs
