### ISSUE TITLE
Fan speed very low but temperature on GPU very high on RX580 anf RX570.

### ISSUE THREAD

**Issue by lodhja** [nanopool/nanominer#119]
Hi all, please help me on how to configure if there is any parameter related to fan speed. When nanopool miner is run, gpu temp are at 80°C but fan runs no more than 20%. Any idea please? Thanks in advance

**Comment by Grumpy-Dwarf** [comment]
You can use some nice tool like MSI AfterBurner to configure fan curve or set fan to some static value.

**Comment by lodhja** [comment]
I am runin it on Linux. Any tool there?

**Comment by Grumpy-Dwarf** [comment]
I personally use this script: https://github.com/grmat/amdgpu-fancontrol
Using 20.30 driver now. Fan control was broken on my system with 20.40 and 20.45 drivers.
