### ISSUE TITLE
No Support for GTX 950s

### ISSUE THREAD

**Issue by SamsoomYT** [nanopool/nanominer#12]
When I tried using the miner on Nvidia GTX 950s with 2 GB each, I get the error stating that:

`2019-04-13 19:53:21: <error> device: 1; Error: not enough memory on GPU 1 to create DAG. Current epoch requires 3039 MB memory for DAG file but this device has only 2048 MB.` and also the same error for my other GPU (Both are running in SLI). Any way I can fix it?

**Comment by broadfashow** [comment]
Get a more powerful GPU, you have 2GB GPU's and the minimum is 3GB for mining eth. The dag file is too large for your GPU, Must use 3GB or larger GPU.

**Comment by Grumpy-Dwarf** [comment]
I'm afraid 2 GB GPUs are not capable to mine Ethereum or Ethereum Classic. You can however mine some other Ethash coin with smaller DAG size (< 2 GB) like Ubiq with nanominer. You can also get good results with Monero using 2 GB cards.
We can do some steps to mine ETH on 2 GB cards but hashrate is awful so we don't release such experimental builds.
