### ISSUE TITLE
Fucked up my system

### ISSUE THREAD

**Issue by SsNipeR1** [nanopool/nanominer#120]
I just wanted to mine some XMR but sounds were strange. I heard any sound with lag. If we do lag with word "welcome" it will sound like "weeeeeeeeeeeeeelcome". Mouse lagged too, but I could stop that program, but there was "boop" sounds every 5-7 seconds. Help me and sorry for bad english

**Comment by hedinajar** [comment]
hy, its normal because xmr use only your cpu and ram. so if your cpu work at 100% with overvoltage and any restriction you can make damage on motherboard and your cpu

**Comment by hedinajar** [comment]
what is your configuration ? mousse and any other app should work slowly if you use all of cpu, you need to monitor the temperature of cpu and motherhead ...sorry for my bad english, i'm french :)

**Comment by Grumpy-Dwarf** [comment]
Please consider using `cpuThreads` option. You can specify number of threads smaller than number of cores you have to have some cores idle and ready for other tasks.
