### ISSUE TITLE
Reboot!

### ISSUE THREAD

**Issue by Rusic7** [nanopool/nanominer#121]
Sometimes, after power errors farm starts without videocards. 
So, I see: 

2020-12-17 10:23:50: <info> Detected 0 devices
2020-12-17 10:23:50: <info> Press enter to continue...

How can I reboot my device automatically in this case?

**Comment by Grumpy-Dwarf** [comment]
I'm afraid miner can't do it. Probably some script can check number of GPUs in system and reboot if there are no devices.

Sometimes GPUs appear several dozens seconds after boot. So running miner in script like this:
```bat
timeout 100
nanominer.exe
```
could be a solution.
