### ISSUE TITLE
 Try to decrease the "memTweak" parameter value for the incorrectly working GPU.

### ISSUE THREAD

**Issue by aicastell** [nanopool/nanominer#124]
Installed nanominer-linux-3.1.4.tar.gz with two RX580 of 8GB.

Today loggin started generating a lot of Rejected Shares, and every time the rejected share counter increases, it appers this warning:

2021-01-03 09:52:27: <warning>  Try to decrease the "memTweak" parameter value for the incorrectly working GPU.

This is the first time this miner gives me this kind of errors. I haven't changed anything related with my setup. 

$ uname -r
4.15.0-128-generic

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

dmesg output shows no errors after mounting the rootfs.

**Comment by perro978** [comment]
Hola in hiveos
Tuning
NanoMiner configuration
![Uploading Screenshot_20210119-175128_Hive OS.jpg…]()

**Comment by Grumpy-Dwarf** [comment]
Try rebooting and decreasing overclocking if this doesn't help.
Probably DAG increased with new epoch and old settings doesn't fit.
