### ISSUE TITLE
Simple User Settings Clarification for ETH minimum payout

### ISSUE THREAD

**Issue by Bonastrebiel** [nanopool/nanominer#126]
I just started mining and reduced the minimum payout from the default 0.2 ETH to 0.1 ETH, that is to not pay the Tx fee. But the information displayed clearly indicates that having a minimum payout of exactly 0.1 ETH a fee will be payed. Therefore I simply suggest to change the greater than sign (>) for the greater or equal to (≥) to avoid any confusion. 
![image](https://user-images.githubusercontent.com/56582637/103668456-66d6fc80-4f77-11eb-8a16-a778b5ed048c.png)

**Comment by nanopool** [comment]
We will sent this information to the pool's department.
