### ISSUE TITLE
Nvidia 3070 not mining

### ISSUE THREAD

**Issue by Voxytech** [nanopool/nanominer#127]
Hello,
I recently setup nanominer with the following content in "config.ini":
[Ethash]
wallet=my_adress
coin=ETH
rigName=PC_fixe

I change the adress in the "config_eth.ini" too, and here is what i've got :
![nano](https://user-images.githubusercontent.com/63168525/103835607-f9b28c80-5086-11eb-91b9-7a4ffb5cf7e5.png)

My video card is detected : 
![card](https://user-images.githubusercontent.com/63168525/103835829-8f4e1c00-5087-11eb-9607-5276f83848a0.png)

Currently, the NVIDIA Driver Version is : 460.89 and the CUDA Version is : 11.2

Thanks you in advance for your help

**Comment by lobsterroboto** [comment]
having the same issue with a 3070 as well 

![Capture](https://user-images.githubusercontent.com/10361164/104110455-75862200-529d-11eb-900c-dfdc16ac7217.PNG)

**Comment by JoeCode42** [comment]
Same problem with v3.1.4 and RTX 3080.
When you open the Task Manager, the GPU's copy module shows a heavy workload, but mining works in the GPU's programmable CUDA module. This is because you are using v3.1.4 instead of v3.1.4-cuda11, which has a different CUDA version.

To fix it, download v3.1.4-cuda11, it will work very well ^^

**Comment by Grumpy-Dwarf** [comment]
Please use `-cuda11` version of miner for Nvidia 30xx GPUs. You can use it with other GPUs too, but it needs up-to-date Nvidia driver. This is why there are two versions of miner. If someone have issues with Nvidia 30xx on `-cuda11` version of miner feel free to reopen this issue.

**Comment by ShineSmile** [comment]
Maybe you could check your address in configuration file. If there is 0x Prefix of it, remove it and restart nanominer.

I found that 0x Prefix will work for f2pool but it makes most of shares become invalid for ethermine pool today.

**Comment by Clava1n** [comment]
Same here. i have all recent releases - 3.2.2 cuda 11, running an Nvidia Geforce 7030, and up to date drivers (27.21.14.6172 is the version given in my device manager. But there is no GPU activity and nothing shown in Nanominer. Only CPU speed.
