### ISSUE TITLE
Nanominer 1.2.1 Crashes

### ISSUE THREAD

**Issue by broadfashow** [nanopool/nanominer#13]
Nanominer 1.2.1 crashes my entire Windows 10 rig. Freezes entire machine and Windows 10 auto reboots. I am running 6x AMD (3) rx 570 8GB and (3) rx 580 8GB. No overclocking at all and using the latest AMD drivers 19.4.1. 

Confirmed crash continues using Nanominer 1.2.1 with the beta Blockchain drivers or AMD 19.4.1 drivers. However the problem is non existent in Nanominer 1.1.1 regardless of the drivers you are using. Works flawlessly.

**Comment by Grumpy-Dwarf** [comment]
I'm pretty sure you mean 1.2.0 was crashing. Please check if 1.2.1 release has fixed the issue.

**Comment by broadfashow** [comment]
Confirmed - 1.2.1 works!

**Comment by broadfashow** [comment]
5 Days running - no issues
