### ISSUE TITLE
Connecting to pools - reconnected to pools about 5-10 times a second

### ISSUE THREAD

**Issue by Yeahnah243** [nanopool/nanominer#133]
Hi there, I'm getting this, can anyone help me out? It would be greatly appreciated
![Nano](https://user-images.githubusercontent.com/77448418/104603814-c9508c80-564a-11eb-859f-82524b26153a.PNG)

**Comment by hedinajar** [comment]
hy, i've had the same problem.... for me its due to your spyware (antivirus) you need to make exception or unistall it...and you need to unleash your internet connection and change some value of gpedit et regedit

**Comment by elfin8er** [comment]
Hmm. Also happening for me on Ubuntu.

**Comment by Grumpy-Dwarf** [comment]
This means networking problem. Either pool drops the connection, either it is dropped by some firewall or even ISP. I would recommend to try same config with other Internet connection. SOme ISPs block pools because of mining viruses.
