### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Rowdydangerous** [nanopool/nanominer#134]
Get access denied even with full permissions given to the .exe and .ini and ran as admin. I'm not sure if anyone else has ran into this or any other additional info you might need.

**Comment by UltimateByte** [comment]
My friend got the same error with an RX 6800.
What's your GPU @Rowdydangerous ?

**Comment by Rowdydangerous** [comment]
It is an RX590.

**Comment by UltimateByte** [comment]
I remote controlled his PC, solved by allowing the .exe in Windows intergrated antivirus.

**Comment by Rowdydangerous** [comment]
Thanks, I'll give that a try tonight.

**Comment by Rowdydangerous** [comment]
It worked for me too thanks.

**Comment by UltimateByte** [comment]
Great, thanks for reporting back. You might wanna close the issue to clear up the issue list for devs :)
