### ISSUE TITLE
unable to use gpu

### ISSUE THREAD

**Issue by gms2009** [nanopool/nanominer#135]
ubuntu 18.04
cuda 10.2
nanominer 3.1.5

./nanominer -d   
shows:
GPU 0  PCI 02:00.0  8119 MB  GeForce GTX 1070
GPU 1  PCI 05:00.0  8119 MB  GeForce GTX 1070

but nanominer config_xmr.ini
only use cpu

config_xmr.ini   has line:
devices = 0,1

**Comment by FibreFoX** [comment]
Thats mentioned at the website, that they only support Monero using CPU:
https://nanominer.org/
![grafik](https://user-images.githubusercontent.com/1042579/104836402-154f3b80-58ae-11eb-8f2d-14ee165d1f9d.png)

**Comment by Grumpy-Dwarf** [comment]
Right, RandomX is CPU-friendly algorithm, it was designed to be poorly supported on GPUs. So it is supported on CPU only in nanominer.
