### ISSUE TITLE
0 Devices Detected Radeon HD 7700 Windows 7 Driver Updated 08/26/2020

### ISSUE THREAD

**Issue by XXXBlueFireXXX** [nanopool/nanominer#137]
Hello All,

I had an old rig sitting around with a Radeon HD 7700 and decided that I wouldn't mind earning a little extra income in Ravencoin. Lucky for me, I'm in a unique situation where power isn't an issue in my apartment so it's simply extra passive income, even though it's an old card.

Unfortunately I fear that it's simply too old for nanominer to support. I'm not sure what to do from this point as I have no clue how the program detects GPUs, so I can't really troubleshoot. Hopefully a dev can help me remedy this problem. If nanominer no longer supports this GPU, does anyone know of a miner that does. Let me know what information to provide if any. Thank you and I appreciate your help.

**Comment by Grumpy-Dwarf** [comment]
Sorry, GPU needs at least 3 GB of on-chip memory for Ravencoin mining.
