### ISSUE TITLE
0 Hashrate, ~112 Watts, and ~50-60% GPU usage on NVIDIA 3080 RTX

### ISSUE THREAD

**Issue by repr0bate** [nanopool/nanominer#139]
Hi there. 

I'm on Windows 10, using a 3080 RTX. Launching nanominer with just my own wallet configured in 'conf.ini' yields: 

- 0 MH/H
- About 109-115 Watts 
- GPU usage at around 50-60%
- Nanominer restarts after about 5 minutes. 

I'm using NVIDIA driver 461.09. I think the stock Window's NVIDIA driver bundles CUDA but I downloaded cuda11 and installed *just* the cuda 11 packages for good measure; no dice. Is it possible this is a nanominer/NVIDIA 461.09 driver related issue or is there something else I can do on my end?

**Comment by ImAccia** [comment]
try setting your gpu fans to 100% with something like msi afterburn etc...
it should stop restarting thus it will start to mine

**Comment by repr0bate** [comment]
@ImAccia Thanks for the reply. I've tried setting the GPU fan to 100% before launching nanominer and it made no difference, unfortunately.

**Comment by bullet36** [comment]
i am having the same issue it will either run for a second and shutdown or 5 min the just shutdown no error in log or anything just shutdown.

**Comment by repr0bate** [comment]
@bullet36 Uh oh! Out of curiosity, did this problem just start occurring for you?

**Comment by bullet36** [comment]
Actually no i have a desktop pc Alienware  r 5 gtx 1070 32 gig mem intel 7 8700 i have only got it to work 2 times and not sure what i did but now it wont work anymore. i know i set it up in the programs(right click-nvidia control panel-then added nano miner to the programs list-then setup there.) i want to say i went to an older driver and it worked but i have not figured out what driver it was.its funny because i have a ASUS rog Zephyrus with 2060 NVidia and an AMD  and it mines with no trouble but my desktop just runs the miner and shuts off after a minute then it will run for 5 min then shuts down i have not overclocked at all. so this has been a problem for me since i started which was the release prior to this one and i have updated.

**Comment by bullet36** [comment]
i also have 3 drives m2 ssd 256 g- 1 tb samsung ssd-1 tb hdd and i have set them all up with 32 gig virtual mem

**Comment by bullet36** [comment]
with you only getting low amount of usage i would say try setting up in the nvidia control panel turn off all ambient occlusion and make sure cuda is set to graphics card not all becuase it might be trying to use your intel graphics if that is what you have also i deleted my intel display driver.

**Comment by repr0bate** [comment]
@bullet36 Thanks for the advice. I've set up the program specifically in NVIDIA control panel, turned off ambient occlusion (it was already off) and made sure CUDA was set to my 3080 RTX specifically (though it's the only graphics card). Unfortunately nothing has worked. I'm beginning to think nanominer isn't playing well with NVIDIA"s latest drivers.

**Comment by bullet36** [comment]
when you start the miner scroll back to top does it say failure to initialize nvml

**Comment by repr0bate** [comment]
@bullet36 Hmm, I'm not seeing that. Double checking the logs reaffirms that I don't see any errors. Here's an additional line in the logs that reveals the cuda and runtime versions: 

`` CUDA driver version is 11.2, runtime version is 10.0``

**Comment by repr0bate** [comment]
I pulled a colossal, massive, dumb dumb. I didn't realize I hadn't downloaded the _cuda version_ of nanominer. Everything works as expected now. Issue closed. 

Hurray.

**Comment by bullet36** [comment]
sweet where did you find it
or should i say what version i noticed on yours it say cuda 11.2 runtime 10
where as mine says 11.2 runtime 11.1

**Comment by repr0bate** [comment]
@bullet36 It's on the download page here on GH. There are Linux and Windows version of nanominer and of those version there are still yet two: a 'normal' one and a 'cuda' version. It says it in the filename when downloading the archive. 

Thanks for the help though.
