### ISSUE TITLE
2070S on Win10 use only 4GB

### ISSUE THREAD

**Issue by gwongis88** [nanopool/nanominer#146]
Is it normal that 2070S GPU is being utilized only 4GB out of 8GB available on the card?
I am using
- Win10
- version 3.1.5 cuda 11
I saw the usage utilization from window task manager performance monitor.

Thanks

**Comment by gwongis88** [comment]
I think I found the answer.   It is what it is.  LOL

**Comment by Grumpy-Dwarf** [comment]
It only needs 4 GB of memory for Ethereum nowdays.
