### ISSUE TITLE
nanominer 3.1.4

### ISSUE THREAD

**Issue by rkshirsagar** [nanopool/nanominer#148]
Hi There,
  I upgraded to Ubuntu 20.04.2 from Ubuntu 16.04 LTS on my 6 GPU rig.  Upgraded amdgpu drivers to the respective Radeon Linux version from amd website, however, when I launch nanonminer for ETH.  It simply exits after logging all the settings in the log file.

Has anyone experienced this?  The nanominer simply exits without any error in the log file.

Can someone help me diagnose where the problem is? 

xxxxxxxxxxx-BTC:/home/robin/nanominer/nanominer-linux-3.1.4# ./nanominer -d
Detected 6 devices:
GPU 0  PCI 01:00.0  8099 MB  Radeon RX 570 Series (Ellesmere)
GPU 1  PCI 02:00.0  8186 MB  Radeon RX 570 Series (Ellesmere)
GPU 2  PCI 03:00.0  8186 MB  Radeon RX 570 Series (Ellesmere)
GPU 3  PCI 05:00.0  8186 MB  Radeon RX 570 Series (Ellesmere)
GPU 4  PCI 06:00.0  8186 MB  Radeon RX 570 Series (Ellesmere)
GPU 5  PCI 07:00.0  8186 MB  Radeon RX 570 Series (Ellesmere)

**Comment by Grumpy-Dwarf** [comment]
Please provide last lines of miner log before it terminates.
What does `echo $?` sayif run right after miner crash? (It shows exit status of previous command.)
Are there any new lines in `dmesg` kernel log after miner terminates?

**Comment by rkshirsagar** [comment]
Installed legacy instead of rocr openCL AMD drivers did it. This can be closed.

**Comment by ryanbuyandsellgames** [comment]
same thing happens in 16.04.6
