### ISSUE TITLE
ARM / Raspberry Pi support

### ISSUE THREAD

**Issue by domi-nik-** [nanopool/nanominer#149]
Hello,
would it be possible to release an arm version for Rasperry Pi 3 and 4 or even the new Macs?
Perhaps it doesn't make sense in terms of revenue but would be a good starting point for newbies and for education purposes.
I could also image that an Cluster of Pis could perhaps do a good mining job.
I suspect that the porting effort will be limited since it was written in golang.
Thank you!

**Comment by Grumpy-Dwarf** [comment]
Our experiments with Raspberry Pi shows it doesn't worth it, hashrates are too low.

We will support powerful ARM-based systems and ARM-based GPU rigs once they will be widely available.

**Comment by bittomine** [comment]
Hum, alright what do I do with my 10.000 Raspberry Pi's now?

**Comment by GlenCooper** [comment]
I would use this on my Pi 4 as well.  I'm sure many others would as well.  Doesn't matter how little of amount is mined; once the user sees their wallet balances gradually increase with the Pi, that would likely be enough to enter the hardware race for better, faster, stronger.

**Comment by FibreFoX** [comment]
@Grumpy-Dwarf are you up to re-open or re-evaluate this feature request? As raspberry pi 4 with 8gb are now available again, and macbooks are having ARM-based CPUs for some device generations now, this might be a good thing to add. Maybe just to mine XMR with it using the CPU.
