### ISSUE TITLE
Request for documentation updates

### ISSUE THREAD

**Issue by UselessGuru** [nanopool/nanominer#15]
Please provide a simple overview table containing 

algo name, min memory required & miner fee

Thank you

**Comment by Grumpy-Dwarf** [comment]
Memory required is tricky, different for Ethash coins for example.
But here is a table in our README:
- 1% of total mining time for Ethash and Ubqhash algorithms (72 seconds per 2 hours);
- 2% for Cuckaroo29 and Cuckarood29 algorithms (144 seconds per 2 hours);
- 2% for RandomX on CPU (144 seconds per 2 hours);
- 5% for RandomHash2 on CPU (180 seconds every hour).
