### ISSUE TITLE
Can't download nanominer-windows-3.1.5-cuda11.zip - Browsers say it is dangerous, a virus or malware

### ISSUE THREAD

**Issue by SirStrivesAlot** [nanopool/nanominer#151]
I have been trying to download nanominer-windows-3.1.5-cuda11.zip on my new PC. I tried in both Brave Browser and Firefox, and I keep getting some sort of notification that it is dangerous or a virus or malware.

I even tried downloading the previous version - nanominer-windows-3.1.4-cuda11.zip and it gave me the same message.

Any thoughts on why this is happening and whether there is some sort of virus or malware in it or whether it's just a false positive from Windows Defender or the browsers themselves?

I appreciate the help. I have nanominer-windows-3.1.4-cuda11.zip on my cryptominer, so I am not sure why I am getting this now. Albeit, I set my cryptominer up about a months ago.

**Comment by SirStrivesAlot** [comment]
See here for additional info - 

https://www.virustotal.com/gui/file/7a2460836203c15bae51e4426ace52213973bc433b325a8624f8604d76d7370b/detection

**Comment by Grumpy-Dwarf** [comment]
You can use miner auto-update feature to download latest miner version from github. Just add
```ini
autoUpdate=true
```
line to your config and launch the miner.
