### ISSUE TITLE
miner restart random 

### ISSUE THREAD

**Issue by luky76** [nanopool/nanominer#153]
os : windows 7
gpus : 1080;    1070;
algo ergo
error : crash gpus random
miner restart

**Comment by luky76** [comment]
[
![ergo error](https://user-images.githubusercontent.com/37260874/107111728-f0216d80-685a-11eb-8119-7bb80f81f645.jpg)
](url)

**Comment by luky76** [comment]
![nanominer issue on ergo](https://user-images.githubusercontent.com/37260874/107120219-08ae7980-6895-11eb-941f-67f2b97971a0.jpg)

**Comment by Grumpy-Dwarf** [comment]
Does it work with stock overclocking settings?

**Comment by AmirSardar683** [comment]
Hello. I exactly have the same problem 
Windows 10 /  GPU 1060 6G  /  ETHASH  /  crash gpu randomly. After 3 mins or 10 mins
![176EEC89-D23E-4093-BE5F-4A27F1550512](https://user-images.githubusercontent.com/78880866/107574272-c3c37380-6c03-11eb-8917-9757487916fb.jpeg)

System exception
Device : 0
CUDA all failed

**Comment by Grumpy-Dwarf** [comment]
This is hardware-specific error. It can be caused by overclocking, insufficient power, bad contact in riser, etc.

**Comment by luky76** [comment]
You closed without solved the problem.

joi, 11 feb. 2021, 15:17 Grumpy Dwarf <notifications@github.com> a scris:

**Comment by Grumpy-Dwarf** [comment]
I can't solve it on nanominer side :(
