### ISSUE TITLE
3.2.0 nanotimer RTX 3060Ti lower hash ratequotes 132 MH/s and I'm seeing approx 50

### ISSUE THREAD

**Issue by browncamo7** [nanopool/nanominer#156]
3.2.0 nanotimer RTX 3060Ti quotes 132 MH/s and I'm seeing approx 50. Why would this be so much lower?

**Comment by Grumpy-Dwarf** [comment]
Do you have rejected shares?

**Comment by Grumpy-Dwarf** [comment]
Please note 142 on stock 3060 ti is for autolykos algorithm (Ergo coin), not Ethereum.

**Comment by Grumpy-Dwarf** [comment]
Feel free to re-open this issue if you have 3060 ti performing only 50 MH/s hashrate on autolykos algorithm (Ergo coin).
