### ISSUE TITLE
Not getting 42MH/s On RX 580 8GB GPU

### ISSUE THREAD

**Issue by Darkminer1** [nanopool/nanominer#157]
As I saw the latest update of nanominer it is saying on rx  @580=42MH/s
This is totally wrong after fully overclocking my gpu i am only getting 32.7 Mh/s
![Nanominer 3 2 0](https://user-images.githubusercontent.com/78716751/107177850-d322a100-69f8-11eb-8b76-090687486391.PNG)

**Comment by Grumpy-Dwarf** [comment]
If you are using Windows please make sure `Compute mode` is enabled in AMD driver settings.

**Comment by Darkminer1** [comment]
Sir I have done it already 1 month ago

**Comment by Grumpy-Dwarf** [comment]
What is hashrate on stock settings?

**Comment by Darkminer1** [comment]
Sir this is for ergo coin
Right?
I am talking about ETH

**Comment by Grumpy-Dwarf** [comment]
32.7 is impressive hashrate for ETH on RX 580. 42 MH/s is hashrate of Ergo coin autolykos algorithm, it's different to Ethash.
So everything is fine with your hashrate on Ethereum.
