### ISSUE TITLE
RTX 2080 incorrectly identified as rtx 2080 SUPER, Algorithm Cuckaroo30 is implemented for device 0

### ISSUE THREAD

**Issue by laurensbainton** [nanopool/nanominer#158]
Cannot mine cortex with rtx 2080 because it is being mistaken for rtx 2080 super

can anyone help?

**Comment by Grumpy-Dwarf** [comment]
Cortex is supported in nanominer with only one specific AMD GPU card, AMD Radeon RX 570 16GB. We don't have plans to support Cortex on other devices. You can miner enything other like Ethereum, Conflux, Raven, Ergo using your GPU and Nanominer.
