### ISSUE TITLE
Request for API change; make reported hash rate more accurate

### ISSUE THREAD

**Issue by UselessGuru** [nanopool/nanominer#16]
Please report the true hash rate in the miner API to make it more accurate.

Some algos, e.g. Cuckaroo29 produce very low hashrates, e.g. 2.7 G/s. The API however reports only integers (3 in this case) which is about 10% off the true value.

**Comment by Grumpy-Dwarf** [comment]
Ethman API uses integers for hashrate. We were avare of this problem and have introduced own [BoringAPI](https://github.com/nanopool/BoringAPI). Please use is for GRIN, see http://127.0.0.1:9090/stats on default nanominer settings.
