### ISSUE TITLE
devices = 0 seems doesnt work

### ISSUE THREAD

**Issue by nonnogatto** [nanopool/nanominer#163]
As title says, using this config for Monero: 
devices = 0
; Address to send funds to.
wallet = ***
; (Optional) Coin to mine.
coin = XMR
; (Optional) Rig (worker) name.
rigName = 2080super
email = ***

but when running it with : nanominer.exe config_xmr.ini
the mining start with CPU for some reason. 
Ideas ?

EDIT: when running nanominer with standard config it starts with my GPU
EDIT2: NVIDIA drivers 461.40
EDIT3: nanominer.exe -d prints :
Detected 1 device:
GPU 0 PCI 01:00.0 8192MB GeForce RTX 2080 SUPER
EDIT4: Im using nanominer_v3.2.2_cuda11 for win64

**Comment by Grumpy-Dwarf** [comment]
XMR mining on GPU is not supported since RandomX hardfork.
