### ISSUE TITLE
Remote managment

### ISSUE THREAD

**Issue by SmallLilDemon** [nanopool/nanominer#168]
Hi, i was wondering if there was a way to remotely start and stop nanominer. The program keeps closing and i want to look at the logs as to why its doing that. I live far away from the miner and i would like to be able to control it from where i live.

**Comment by MbahAgis** [comment]
Hello, 
Unfortunately we have to set port forwarding on our router so we can control it remotely from outside network. 
In easy way, you need to try [Hive OS](https://hiveos.farm?ref=417084)
We can do overclocking, remoting, and almost everything to keep the rig healthy 😁
