### ISSUE TITLE
MSI RX 480 4gb only 8 MH/s on nanominer

### ISSUE THREAD

**Issue by sunnyoil** [nanopool/nanominer#185]
Hi, I'm new to mining. have my old pc and getting it to run but i have only 8MHs. On my gaming pc with 1080 is 30mhs with pill.
I've been trying to increase it but its stuck on 8 even with afterburner. amd software is 16.9.2 and doesnt have compute mode but if i upgrade it to new nanominer wont work. do i need to instal every update for amd till it works and gas compute mode or am i missing something big?

specs are:
 Asus Sabertooth x79
Procesor : Intel i7 4820k 3.70 / 3,90 GHZ 4C/8T
GPU: MSI RX 480 Gaming X 
ram: HyperX 32GB DDR3 1866 MHZ (4x8)
HDD : Western Digital Black 500GB SATA 3 7200rpm 64MB (brzi hard disk)
Thermaltake Smart SE 530W 87% Bronze semi-modular
 OS: Windows 10 Pro (original,)

thanks in advance

P.S. when i start nanominer it say some hardware is still tuning so hasrate may be lower than expected

**Comment by danielehrhardt** [comment]
You can check if you activated compute mode for your AMD GPU. 
https://minerstat.com/help/how-to-enable-amd-compute-mode

Other than that your 4GB is not enough to mine Ethereum.

**Comment by sunnyoil** [comment]
i was playing with software and got to enable compute mode but its on 10 now...yeah i was wondering if my card was old by now, because im so late with mining...thank you anyways
