### ISSUE TITLE
out of memory increased the virtual memory

### ISSUE THREAD

**Issue by shabbyster** [nanopool/nanominer#20]
Hi
I am mining eth with 12 gtx 1070 cards rig. I am getting 2 errors. One out of memory please increased the virtual memory. How can i increase the virtual memory? I am using the latest version 1.2.4 

2nd error

system exception 
device 5

thanks

**Comment by broadfashow** [comment]
Increasing Virtual Memory in Windows 10
1. Go to the Start Menu and click on Settings.
2, Type performance.
3, Choose Adjust the appearance and performance of Windows.
4. In the new window, go to the Advanced tab and under the Virtual memory section, 
5. Click on Change.
6. Uncheck the Automatically manage paging file size for all drives box at the top of the same windows and then click on Custom size.
Enter the Recommended value in the Initial Size box, and a larger figure in the Maximum size box.
Click OK to save the new settings.

**Comment by broadfashow** [comment]
Also - for stability, I would recommend using 1.2.4 (latest) version of nanominer

**Comment by Grumpy-Dwarf** [comment]
The amount of virtual memory should be size of DAG * number of cards for Ethereum mining. I recommend to set up 37 GB swap for 12 cards. It will not be touched by system but this a workaround for design decisions of Nvidia made in "Nobody will have more GPU memory on system than virtual memory available!" times.

**Comment by shabbyster** [comment]
Thanks miner is working perfectly now. You guys are the best
