### ISSUE TITLE
The mining rig on nanopool is stop without any problem

### ISSUE THREAD

**Issue by FlanBinFlan** [nanopool/nanominer#209]
After a approximately 4 to 8 hour the mining on nanopool stop without any reason and the rig stop mining.

**Comment by doganate** [comment]
same issue here

**Comment by FlanBinFlan** [comment]
> same issue here

Dose it happend on pc or mining rig?

**Comment by FlanBinFlan** [comment]
> > same issue here
> 
> Dose it happend on pc or mining rig?

Does it happend before or just with new version?

**Comment by doganate** [comment]
> > same issue here
> 
> Dose it happend on pc or mining rig?

Pc. 
12gb vram enabled
32gb ram
3600 ryzen 5
5700xt xfx thicc iii

**Comment by FlanBinFlan** [comment]
> > > same issue here
> > 
> > 
> > Dose it happend on pc or mining rig?
> 
> Pc.
> 12gb vram enabled
> 32gb ram
> 3600 ryzen 5
> 5700xt xfx thicc iii

Are you new on mining or from long time?

**Comment by doganate** [comment]
I'm new, It stops whenever the DevFee starts so it must be a problem with that.

**Comment by FlanBinFlan** [comment]
> I'm new, It stops whenever the DevFee starts so it must be a problem with that.

I found link that they have DevFee problem and they tried to solve it.
https://forum.ethereum.org/discussion/17422/claymore-devfee-couldnt-connect-to-stratum-restarts-miner-complains-not-enough-gpu-memory-dag

**Comment by FlanBinFlan** [comment]
closed it by mistake
