### ISSUE TITLE
i have a dude, kernel build failed.

### ISSUE THREAD

**Issue by luisx184** [nanopool/nanominer#21]
hello, I tested nanominer 1.3 and with these cards:  Asus R7 370 4gb card ( 6 ) gpu.
 and gave me this error, please any help?. 

![image](https://user-images.githubusercontent.com/36945258/57726094-acd1a500-765c-11e9-8ff9-beff56bbc157.png)

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting. What driver version do you have?

**Comment by luisx184** [comment]
Hello, the lastes version by the asus enterpise.

Crimson 22.19.162.4 

Thank's for reply.
 
![image](https://user-images.githubusercontent.com/36945258/57806962-3ac99080-772e-11e9-9588-3681342920ed.png)

**Comment by Grumpy-Dwarf** [comment]
Please check if [nanominer 1.3.1](https://github.com/nanopool/nanominer/releases/tag/v1.3.1) release has this issue fixed.

**Comment by luisx184** [comment]
Hi, I'm sorry to respond very late, it works excellent, thank you very much for the fix.
