### ISSUE TITLE
BUG - Hashrate going down -> minHashrate command not working

### ISSUE THREAD

**Issue by anemlife** [nanopool/nanominer#221]
Hello,

Been doing the fix to unlock the hashrate of a 3060. It goes well but everyday after a few hours the reported hashrate goes down (from about 43mhs to 17mhs every time) and it won't go back to 43mhs if I don't restart nanominer. 

I've been adding the "minhashrate" command line yesterday (to automatically restart the miner when going under 35mhs) to my config file but it's not making any difference. 

Any idea about what could cause this? It's pretty boring as I can't always restart the rig immediately. (when I'm at work) Also the energy consumption doesn't goes down while the hashrate does so It's kind of making me "losing" gains... 

See the graphics below, every time the black line drops it's because of this unknown reason...

![Capture d’écran 2021-05-04 à 13 58 17](https://user-images.githubusercontent.com/71634523/117000387-462e7180-ace1-11eb-82d6-e3ddcc61cb01.png)

Thanks

**Comment by Raptor2213** [comment]
Based off of your relatively low speed, I'm guessing it could be an issue with your overclock.

1. Turn off overclock while the DAG file creates.
2. After it creates, try 65% power, -500 core clock, +1200 memory clock.

**Comment by anemlife** [comment]
Thanks for the reply! Actually I found why the restart function wasn't working, I forgot the s (restarts and not restart when typing the function) and also It was written in the wrong order in the config file. Now everything works as expected :)

(the low speed I'm getting is normal, I'm doing some temperature tests as this GPU gets too hot with max overclocking in my opinion)

Thanks, closing the issue!
