### ISSUE TITLE
Monero don't have the money

### ISSUE THREAD

**Issue by 532609499** [nanopool/nanominer#23]
[CryptoNightR]
wallet = 466P4Z7Z5H7duWXvGVWTH4KeFQ1ry***
paymentId = ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
rigName = rig1
email = 123@qq.com
pool1 = xmr-eu1.nanopool.org:14433
pool2 = xmr-eu2.nanopool.org:14433
pool3 = xmr-us-east1.nanopool.org:14433
pool4 = xmr-us-west1.nanopool.org:14433
pool5 = xmr-asia1.nanopool.org:14433
powerLimits = -20

I use 1060 6g 450H/s  , not seeing the money :3

**Comment by Grumpy-Dwarf** [comment]
Please check your paymentid, did you hide it or use ffffff...ffff value which is surely wrong?
Are there accepted shares on your account page on nanopool? There is a balance on account page, payment id done  once balance riches minimal limit.
You can email pool support  xmr@nanopool.org for solving some account specific issues.

**Comment by Grumpy-Dwarf** [comment]
Closing because this is a configuration issue.
