### ISSUE TITLE
hashtate sudenlly down when mining ravencoin with nanopool

### ISSUE THREAD

**Issue by moshemman** [nanopool/nanominer#273]
I mining ravencoine on Nvidia GTX 1650 GPU with nanominer and nanopool.
for mor than 3 month it did 7 MH/s, now it did also 7 MH/h but sudenlly and with no reasone it down to 1.8 MH/s.
when i restart the nanominer program or my restart the PC it did back 7 MH/s.
i tried with NBminer and same issue repruduced.
any one have the same issue? 
is this pool issue? or maybe hard ware?

NOTE: no temperature issue, mining other coins is OK

**Comment by Grumpy-Dwarf** [comment]
I believe this is hardware issue.
