### ISSUE TITLE
GPU_SINGLE_ALLOC_PERCENT error

### ISSUE THREAD

**Issue by HariharanM69** [nanopool/nanominer#276]
2021-Sep-13 01:21:51: Log path: ./logs/
2021-Sep-13 01:21:51: Log is written to file
2021-Sep-13 01:21:51: GPU watchdog is enabled
2021-Sep-13 01:21:51: Never calling reboot.bat (always restarting the miner in case of errors). 
2021-Sep-13 01:21:51: Setting up algorithm: Kawpow
2021-Sep-13 01:21:52: Connecting to pools...
2021-Sep-13 01:21:52: Connected to pool: kp.unmineable.com:3333 | IP: 174.138.16.96
2021-Sep-13 01:21:53: New job from kp.unmineable.com:3333 | share difficulty = 4 GH, epoch 256 (3071 MB)
2021-Sep-13 01:21:53: Raven - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:01
2021-Sep-13 01:21:53:  fan 0%
2021-Sep-13 01:21:54: Error: could not allocate memory on GPU 0 to create DAG. Current epoch requires 3071 MB memory for DAG but there is only 2079 MB allowed to allocate in single buffer. Try setting GPU_SINGLE_ALLOC_PERCENT environment variable to 100.
2021-Sep-13 01:22:06: Terminating, please wait ...

This is the first problem I faced. Then I add the GPU_SINGLE_ALLOC_PERCENT 100 into config.ini and it shows another problem which is :
![image](https://user-images.githubusercontent.com/73754075/132997169-b758f3f7-7d0b-4a88-9a5a-cc2f99155a00.png)

**Comment by Grumpy-Dwarf** [comment]
`GPU_SINGLE_ALLOC_PERCENT ` should not be in config file. It should be added as an [environment variable](https://en.wikipedia.org/wiki/Environment_variable).
