### ISSUE TITLE
Worker name, fantasy

### ISSUE THREAD

**Issue by PSLLSP** [nanopool/nanominer#299]
I used T-Rex miner but I decided to try nanominer. I see a small problem with worker name (rig name). It is cosmetic issue but it is a bug... Why is this a bug? This worker name could be used for other purpose, as a switch and when nanominer is creative (it modifies user input), it could be a problem. If you think it is good idea to overwrite user config, add a command line switch to control such feature. I do not like that nanominer overwrites my config...

Issue: worker name is configured as `HIVEOS-2` but I see at pool stat page that nanominer sends `HIVEOS-2_Snow_White_79692dd7` (nanominer extends worker name with text **_Snow_White_79692dd7**).

Nanominer config:

```
=== /hive/miners/nanominer/3.4.2-cuda111/config.ini =================================================
webport=3339
mport=0
logPath=/var/log/miner/nanominer/nanominer.log
restarts=0
[firopow]
wallet=aLGD3gV4Z5Az25RbEjU4pBKzyv3R2LvbcZ.HIVEOS-2
rigPassword=x
pool1=firo.2miners.com:8181
```

UPDATE:
I modified configuration and corect worker name is sent to the pool:
```
=== /hive/miners/nanominer/3.4.2-cuda111/config.ini =================================================
webport=3339
mport=0
logPath=/var/log/miner/nanominer/nanominer.log
restarts=0
[firopow]
wallet=aLGD3gV4Z5Az25RbEjU4pBKzyv3R2LvbcZ
rigPassword=x
pool1=firo.2miners.com:8181
rigName=HIVEOS-2
```

**Comment by Grumpy-Dwarf** [comment]
This evidence is not a bug. Nanominer works as intended.
