### ISSUE TITLE
Problem with new nanominer 

### ISSUE THREAD

**Issue by Mostovch** [nanopool/nanominer#3]
After running thiis "NEW" nanominer-windows-1.0.5, it is starting to do something, I mean:
- loading many symbols,
- everything is green
- after few minutes my AMD wattman telling Reset setting?
It is possible to explain or provide any manual khow to use this nanominer from clean Windows?

Previous miner vas really more better

**Comment by Mostovch** [comment]
And my hashrate double is down
2019-01-22 23:31:24: [Statistics] Monero last 10 min - GPU 0: 320.630 H/s, GPU 1: 329.782 H/s, GPU 2: 259.721 H/s, GPU 3: 332.745 H/s, GPU 4: 334.780 H/s, GPU 5: 324.862 H/s, GPU 6: 322.457 H/s, GPU 7: 39.527 H/s, GPU 8: 322.304 H/s, GPU 9: 321.524 H/s, GPU 10: 311.557 H/s. Total: 3.216 kH/s.

**Comment by Mostovch** [comment]
My config is:
; nanominer.exe config.ini
[CryptoNightv8]
wallet = ******
rigName = AS
email = ____________@gmail.com
pool1 = xmr-eu1.nanopool.org:14433
pool2 = xmr-eu2.nanopool.org:14433
pool3 = xmr-us-east1.nanopool.org:14433
pool4 = xmr-us-west1.nanopool.org:14433
pool5 = xmr-asia1.nanopool.org:14433

**Comment by Mostovch** [comment]
It is possible use XMR-Stark as before?

**Comment by Mostovch** [comment]
Hi
I use last one of nanominer.
AMD Sapphire RX 570 4 GB - standart h/r is 600. 
When I start to use with same driver configuration your nanominer, I miss double resources, but power my card use same before.

**Comment by Mostovch** [comment]
Another problem: When I start try use your nanominer with vega 56, your application is rise up only second time, the first time  Windows 10 showing all time the mistake (about stopping the programm) and closing current application

**Comment by CARPI212715** [comment]
I have 2 rigs 

Rig 1  5x rx570rx msi 29M/hz doesnt miss a beat using nanominer 1.1.1
Rig 2 x3 Asus x1 rx570msi x1sapphire " miner finds shares but doesnt do naything with them

error :connection was closed (index: 0)
and
could not connect to any pools

really breaking my brain please help

cheers

**Comment by Grumpy-Dwarf** [comment]
We've dropped CryptoNight algorithms support since XMR switched to RandomX.
