### ISSUE TITLE
autoUpdate=true resulting in infinite restart loop

### ISSUE THREAD

**Issue by Michael-Monaldi** [nanopool/nanominer#300]
Miner say .3.4.3 is available and downloading update at launch, restarts - infinite loop.

From releases page it appear this version is not out yet, so miner is attempting to access update that arent out yet...

Possibly it is looking on the dev branch?

This issue repeated on two separate machines - autoUpdate=false resolves the issue

**Comment by chrisywong** [comment]
Can confirm, same thing on my machine.

**Comment by Grumpy-Dwarf** [comment]
Fixed!
