### ISSUE TITLE
Proxy Feature Request

### ISSUE THREAD

**Issue by ShineSmile** [nanopool/nanominer#310]
For some reason, many users couldn't connect to mining pool from yesterday.
Shall we request HTTP/Socks Proxy feature for this situation?

**Comment by tempestLXC** [comment]
I have the same problem

**Comment by ShineSmile** [comment]
I found that miner use different protocol to communicate with pool.
The port-forward redirect proxy will work.
I will close the issue.

**Comment by zhaxiaoping** [comment]
能不能发一个使用代理服务器的案例，是改config置配文件吗？如何改参数
