### ISSUE TITLE
Verus algo no longer submitting blocks

### ISSUE THREAD

**Issue by Oink70** [nanopool/nanominer#312]
After the Verus mainnet upgrade at block 1796400, the solution version dynamically changed. Pools supply the correct solution number to the connected miners.

Nanominer however remains at the previous solution, most likely because the solution number is hardcoded and the information from the mining pool is ignored / not processed, resulting in every work submission to fail with a "invalid solution version".

**Comment by UselessGuru** [comment]
![image](https://user-images.githubusercontent.com/30080938/144239804-a44373cb-d43e-4925-b765-c85e371068ac.png)

**Comment by Grumpy-Dwarf** [comment]
Fixed.
