### ISSUE TITLE
Nanopool and LHR

### ISSUE THREAD

**Issue by CAW555** [nanopool/nanominer#319]
No matter which version we use, the etash loads with teh LHR in default, when code is used to stop lhr (lhr=-1) it does nothing
I have several older Nvidia cards that are not affected by LHR but nanopool is knocking them down to 71.5% by default. Nanopool doesn't seem to accept they have an issue. Does anyone else see these problems?

**Comment by Grumpy-Dwarf** [comment]
LHR unlock is not implemented in versions before 3.5.0.

**Comment by CAW555** [comment]
Hi, While it was implemented at 3.5.0 it affects all versions please see the enclosed log showing version 3.4.3 cuda11 and stating version 3.5 is available, while also implementing LHR !! hence my original question !
[log_2021-12-15_14-25-14 nanominer.docx](https://github.com/nanopool/nanominer/files/7729434/log_2021-12-15_14-25-14.nanominer.docx)
