### ISSUE TITLE
I cant get any hashrate more than 10 

### ISSUE THREAD

**Issue by yigitako** [nanopool/nanominer#32]
I have got rx 480 4gb and I cant get hashrate more than 10 I saw that some people got 30 40 hashrate with a single rx 480 why my gpu produce 11 hashrate ?

**Comment by Grumpy-Dwarf** [comment]
Please switch your GPU to Compute workload instead of graphics. https://www.amd.com/en/support/kb/faq/dh-024
This should give you 22-24 MH/s. Up to 30-32 MH/s can be possible in case of overclocking and memory timings tuning.

**Comment by yigitako** [comment]
Now I have got 24-23 hashrate
