### ISSUE TITLE
Nanominer ETH not working

### ISSUE THREAD

**Issue by madding1602** [nanopool/nanominer#323]
Hi. I have a ROG G531GT laptop with a gtx 1650 and an i7 9750H. I'm trying to start nanominer, but I get 0 MHs on the programme. Any help? I reinstalled Nvidia graphics last version, but did nothing

**Comment by FibreFoX** [comment]
I assume you are having the ` NVIDIA® GeForce® GTX 1650 4GB GDDR5` model? If so, you are unable to mine ETH, as your machine does not have enough VRAM, for ETH you need 6GB due to the DAG-size. You probably are getting some errors on program start, where it tells you "not enough memory".

**Comment by FibreFoX** [comment]
@madding1602 any update?

**Comment by madding1602** [comment]
Hi. I just couldn't get ETH to work, so I decided not to mine. And I did
