### ISSUE TITLE
RX 5700 EtcHash, Ethash, FiroPoW & KawPow: Could not make binaries

### ISSUE THREAD

**Issue by UselessGuru** [nanopool/nanominer#329]
Version 3.5.2-cuda11
2022-Jan-11 18:56:59: Started web interface on port 4001 without a password.
2022-Jan-11 18:56:59: CUDA driver version is 11.5, runtime version is 11.1
Detected 4 devices
GPU 0 PCI 01:00.0, Platform: OpenCL, Name: Radeon RX 580 Series (Ellesmere), 8192 MB available
GPU 1 PCI 09:00.0, Platform: OpenCL, Name: AMD Radeon RX 5700 XT (gfx1010), 8176 MB available
GPU 2 PCI 0b:00.0, Platform: CUDA, Name: NVIDIA GeForce GTX 1660 SUPER, 6143 MB available
GPU 3 PCI 10:00.0, Platform: CUDA, Name: NVIDIA GeForce GT 1030, 2047 MB available
-------------------Ethash:------------------
Currency: Ethereum Classic
....
2022-Jan-11 18:57:02: New job from europe.etchash-hub.miningpoolhub.com:20615 | share difficulty = 12885 MH, epoch 238 (2927 MB)
**2022-Jan-11 18:57:02: Could not make binaries for gfx1010**

Driver Version 27.20.12027.1001 / 3110.7 (PAL,LC) / Windows 11

**Comment by UselessGuru** [comment]
Any plans to fix this?

**Comment by UselessGuru** [comment]
Same issue with version 3.6.0

**Comment by jman0121** [comment]
I'm having the same issue with a 6500 XT

**Comment by jman0121** [comment]
I have this issue with a 6500 XT also - could no make binaries for gfx1034

**Comment by UselessGuru** [comment]
Issue is fixed with NanoMiner version 3.6.1 & AMD driver 30.0.15019.1005 (AMD-Software-Adrenalin-Edition-22.3.2-Win10-Win11-March24)
