### ISSUE TITLE
Crash minig monero

### ISSUE THREAD

**Issue by FakeKoder** [nanopool/nanominer#339]
Crash programm when minin monero. 
2022-Apr-11 14:38:16:                                    _                 
2022-Apr-11 14:38:16:  _ __   __ _ _ __   ___  _ __ ___ (_)_ __   ___ _ __ 
2022-Apr-11 14:38:16: | '_ \ / _` | '_ \ / _ \| '_ ` _ \| | '_ \ / _ \ '__|
2022-Apr-11 14:38:16: | | | | (_| | | | | (_) | | | | | | | | | |  __/ |   
2022-Apr-11 14:38:16: |_| |_|\__,_|_| |_|\___/|_| |_| |_|_|_| |_|\___|_|   
2022-Apr-11 14:38:16: 
2022-Apr-11 14:38:16: Version 3.6.0
2022-Apr-11 14:38:16: Started EthMan server on port 3333 without a password (read-only mode).
2022-Apr-11 14:38:16: Started web interface on port 9090 without a password.
2022-Apr-11 14:38:16: ------------------RandomX:------------------
2022-Apr-11 14:38:16: Currency: Monero
2022-Apr-11 14:38:16: Wallet: xxx SuRTnnm
2022-Apr-11 14:38:16: Rig name: worker_XMR
2022-Apr-11 14:38:16: Email: xxx 2022-Apr-11 14:38:16: Hashrate threshold to restart miner is not set
2022-Apr-11 14:38:16: Number of rejected shares per hour to restart miner is not set
2022-Apr-11 14:38:16: Using CPU threads: 4
2022-Apr-11 14:38:16: Added pool: xmr-eu1.nanopool.org:14433
2022-Apr-11 14:38:16: Added pool: xmr-eu2.nanopool.org:14433
2022-Apr-11 14:38:16: Added pool: xmr-jp1.nanopool.org:14433
2022-Apr-11 14:38:16: Added pool: xmr-us-east1.nanopool.org:14433
2022-Apr-11 14:38:16: Added pool: xmr-us-west1.nanopool.org:14433
2022-Apr-11 14:38:16: Added pool: xmr-asia1.nanopool.org:14433
2022-Apr-11 14:38:16: Added pool: xmr-au1.nanopool.org:14433
2022-Apr-11 14:38:16: Auto pool sorting is enabled
2022-Apr-11 14:38:16: -------------Common parameters:-------------
2022-Apr-11 14:38:16: Log path: ./logs/
2022-Apr-11 14:38:16: Log is written to file
2022-Apr-11 14:38:16: GPU watchdog is enabled
2022-Apr-11 14:38:16: Never calling reboot.bat (always restarting the miner in case of errors). 
2022-Apr-11 14:38:16: Setting up algorithm: RandomX
2022-Apr-11 14:38:16: Connecting to pools...
2022-Apr-11 14:38:17: Connected to pool: xmr-eu1.nanopool.org:14433 | IP: 51.15.65.182 | ping: 223 ms.
2022-Apr-11 14:38:17: CPU:         Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz | AVX2: no | SSSE3: yes | AES: yes
2022-Apr-11 14:38:17: New job from xmr-eu1.nanopool.org:14433 | share difficulty = 480 kH
2022-Apr-11 14:38:17: Monero - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:00
2022-Apr-11 14:38:17: Updating dataset...
2022-Apr-11 14:38:18: [RandomX] ~~~~~~ DevFee begin ~~~~~~

**Comment by Grumpy-Dwarf** [comment]
Fixed in nanominer 3.6.1.
