### ISSUE TITLE
NanoMiner-1.4.1-Windows-Detected 0 devices

### ISSUE THREAD

**Issue by ragotnicolas** [nanopool/nanominer#36]
Hello,
I have a problem with nanominer 1.4.1 for Windows.
The devices are not detected.
It's work with finminer version 2.2.5.
Could you please tell me what to do to solve this issue ?
Do you need some logs ?
[log_2019-07-06_12-16-53.zip](https://github.com/nanopool/nanominer/files/3364606/log_2019-07-06_12-16-53.zip)

![image](https://user-images.githubusercontent.com/52598059/60754878-082e6c80-9fe8-11e9-81b2-473ad773706f.png)

**Comment by Grumpy-Dwarf** [comment]
We now support RTX Nvidia devices so need up-to date Nvidia driver which supports CUDA 10. Please try updating to the latest Nvidia driver, need 411+ version in order to work.

**Comment by ragotnicolas** [comment]
Thank you, it's better now, I can start the application to mine.
We can close this case.
