### ISSUE TITLE
Error message - "Monero: trying to use "Stratum"

### ISSUE THREAD

**Issue by xmrminer1** [nanopool/nanominer#373]
This morning my 3 computers that mine XMR (Monero) using nanominer, all started having the same error message: "Monero: trying to use stratum mining protocol... to disable this behavior, specify: protocol=JSON-RPC"

It also sometimes says "there were no new jobs in the past 10 minutes" sometimes.

I have no idea where this came from, didn't have any changes made to my network or computers. The 3 computers were all mining 100% fine when I went to bed. I woke up to that error on all three computers, and noticed it happened at 3:30 am EST,  Thursday the 20th of October. Any ideas on what caused this, and what I can do to fix it?

Edit: might be relevant that I recently downloaded Malwarebytes to clean up my computer, but I had allowed all the nanomining stuff to be allowed, and not quarantined, or so I thought.

**Comment by xmrminer1** [comment]
Issue resolved

**Comment by timkicker** [comment]
How did you resolve this issue?
