### ISSUE TITLE
Dual mining Raven and Zilliqa doesn't work

### ISSUE THREAD

**Issue by Onzenuub** [nanopool/nanominer#379]
Config.ini =
[KawPow]
coin = RVN
wallet = REr*************************
rigName = *******
email = ******************l
sortPools=true
autoupdate=true
[zil]
wallet = zil*************************
zilEpoch = 0; number of DAG epoch for caching
pool1 = eu.ezil.me:5555
pool2 = us-east.ezil.me:5555
pool3 = us-west.ezil.me:5555
pool4 = asia.ezil.me:5555
rigName = **********
sortPools=true
email = ********************

Raven mining does work, Zilliqa mining   " Could not connect to any pools." 

What is wrong???

**Comment by Grumpy-Dwarf** [comment]
You are using outdated port number. Please change 5555 to 4444.
