### ISSUE TITLE
 nanominer 1.50

### ISSUE THREAD

**Issue by sofy71** [nanopool/nanominer#38]
Cuckaroo29 algorithm or coin=grin 

Support for Nvidia 6+ GB cards on Cuckaroo29/Cuckarood29 algorithms.
It Works

...but the only Issue - hash only +- 4g/s for GTX 1080TI (7 - 8 g/s normal) 
...and quite difficult to get share above 2.. per minute or two

Hopefully will get over it

Thank you

**Comment by Grumpy-Dwarf** [comment]
Cuckarood29 algorithm is dead now since GRIN hardforked to Cuckaroom29.
