### ISSUE TITLE
Intel Arc A750

### ISSUE THREAD

**Issue by Rom1122** [nanopool/nanominer#380]
Hi, tried Nanominer but the Intel Arc A750 gets not detected.
Also the -d command says, no GPU detected.
Its the Asrock OC Edition.
Is it not supported right now and just the normal A750 and A380?

![image](https://user-images.githubusercontent.com/120304146/207127763-aaaf6b5b-ee0d-4978-b657-f0f678f26770.png)

Greetz

**Comment by Grumpy-Dwarf** [comment]
Seems you did not install Intel OpenCL runtime. You can download it from [Intel web site](https://www.intel.com/content/www/us/en/developer/tools/opencl-sdk/overview.html)

**Comment by Rom1122** [comment]
Its installed autoimatically with the Graphics Driver.
So, maybe another solution?

With lolminer it works,.....

You can read it here "Intel® Graphics Compute Runtime for OpenCL™ Driver is included with the Intel® Graphics Driver package for Windows* OS."

https://www.intel.com/content/www/us/en/developer/articles/tool/opencl-drivers.html

Greetz

**Comment by Darklegion1978** [comment]
Ok, no other solution, it still not works with nanominer, so i use lolminer instead. works like a charme.

Greetz
