### ISSUE TITLE
3.8.0 and hashrate in e+00 format in API?

### ISSUE THREAD

**Issue by tymoteuszrogalewski** [nanopool/nanominer#385]
"Hashrate": "5.191341e+07"
...that is hashrate presented in API since now. Can you bring back presented value to "normal" mode like "5.1913" ? ;-)

**Comment by Grumpy-Dwarf** [comment]
What API do you mean? And what coin? Our Boring API or EthMan? I did not change any code linked with API. Boring API shows hashrate in exponential form since its inception/

**Comment by tymoteuszrogalewski** [comment]
Sorry. Problem was something else ;P
Best regards.
