### ISSUE TITLE
v3.8.1 (Windows): command line parameter '-devices ' no longer working

### ISSUE THREAD

**Issue by UselessGuru** [nanopool/nanominer#387]
In v3.7.7 I could successfully select the mining devices with '-devices 1,2,3....'

This does no longer work with v3.8.1.
No matter what values I set for '-devices' NanoMiner will always use all devices.

**Comment by Grumpy-Dwarf** [comment]
I tried `-devices` option and it seems working. What is your full command line?

**Comment by UselessGuru** [comment]
> What is your full command line?

One example:
`NanoMiner-v3.8.1\nanominer.exe -algo Etchash -pool1 etchash.auto.nicehash.com:9200 -useSSL false -wallet ################################ -rigName '##############' -rigPassword x -algo Kaspa -pool1 kheavyhash.eu.mine.zergpool.com:5555 -useSSL false -wallet ##################### -rigName '##################' -rigPassword c=BTC,ID=#########,pl=0 -mport 0 -webPort 4001 -checkForUpdates false -noLog true -watchdog false **-devices 1**`

I only select ONE device, but the DAG is built on may devices:
                                   _
 _ __   __ _ _ __   ___  _ __ ___ (_)_ __   ___ _ __
| '_ \ / _` | '_ \ / _ \| '_ ` _ \| | '_ \ / _ \ '__|
| | | | (_| | | | | (_) | | | | | | | | | |  __/ |
|_| |_|\__,_|_| |_|\___/|_| |_| |_|_|_| |_|\___|_|

Version 3.8.1-windows
2023-May-19 00:10:08: Started web interface on port 4001 without a password.
2023-May-19 00:10:08: NVIDIA driver version: 531.79 (12.1)
Detected 5 devices
GPU 0 PCI 01:00.0, Platform: OpenCL, Name: Radeon RX 580 Series (Ellesmere), 8192 MB available
GPU 1 PCI 09:00.0, Platform: OpenCL, Name: AMD Radeon RX 5700 XT (gfx1010), 8176 MB available
GPU 2 PCI 0b:00.0, Platform: CUDA, Name: NVIDIA GeForce GTX 1660 SUPER, 6143 MB available
GPU 3 PCI 0c:00.0, Platform: CUDA, Name: NVIDIA GeForce GT 1030, 2047 MB available
GPU 4 PCI 10:00.0, Platform: CUDA, Name: NVIDIA GeForce GTX 750 Ti, 2047 MB available
------------------Etchash:------------------
Currency: Ethereum Classic
Wallet: 33hZYX8iFg5zm9E3geqrNgeP6TMzszZk5R
Rig name: Blackbox
Email was not set.
Rig password: x
Hashrate threshold to restart miner is not set
Number of rejected shares per hour to restart miner is not set
Added pool: etchash.auto.nicehash.com:9200
Auto pool sorting is disabled
Using all GPU devices
-----------------Heavyhash:-----------------
Currency: Kaspa
Wallet: 1GPSq8txFnyrYdXL8t6S94mYdF8cGqVQJF
Rig name: 1GPSq8txFnyrYdXL8t6S94mYdF8cGqVQJF
Email was not set.
Rig password: c=BTC,ID=Blackbox,pl=0
Hashrate threshold to restart miner is not set
Number of rejected shares per hour to restart miner is not set
Added pool: kheavyhash.eu.mine.zergpool.com:5555
Auto pool sorting is disabled
Devices: 1
-------------Common parameters:-------------
Log path: ./logs/
Log is written to file
GPU watchdog is disabled
Never calling reboot.bat (always restarting the miner in case of errors).
2023-May-19 00:10:09: Setting up algorithm: Etchash
2023-May-19 00:10:09: Setting up algorithm: Heavyhash
2023-May-19 00:10:09: Connecting to pools...
2023-May-19 00:10:09: Connected to pool: kheavyhash.eu.mine.zergpool.com:5555 | IP: 141.95.55.97
2023-May-19 00:10:09: New job from kheavyhash.eu.mine.zergpool.com:5555 | share difficulty = 4 GH
2023-May-19 00:10:10: Connecting to pools...
2023-May-19 00:10:10: Connected to pool: etchash.auto.nicehash.com:9200 | IP: 34.160.163.23
2023-May-19 00:10:10: Ethereum Classic: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2023-May-19 00:10:10: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:10: Could not find the "WinAMDTweak\WinAMDTweak.exe" executable file.
2023-May-19 00:10:10: New job from etchash.auto.nicehash.com:9200 | share difficulty = 2 GH, epoch 292 (3359 MB)
2023-May-19 00:10:10: Resetting clocks for device #4...
2023-May-19 00:10:10: Resetting clocks for device #4...
2023-May-19 00:10:10: Resetting clocks for device #4 is done.
2023-May-19 00:10:10: Resetting clocks for device #4...
2023-May-19 00:10:10: Resetting clocks for device #4 is done.
2023-May-19 00:10:10: Resetting clocks for device #4 is done.
2023-May-19 00:10:10: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:10: Resetting clocks for device #4...
2023-May-19 00:10:10: Resetting clocks for device #4...
2023-May-19 00:10:10: Resetting clocks for device #4 is done.
2023-May-19 00:10:10: Resetting clocks for device #4 is done.
2023-May-19 00:10:11: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:11: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:12: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:12: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:13: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:13: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:14: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:14: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:15: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:15: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:16: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:16: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:17: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:17: **GPU1:** 3359 MB DAG generated in 4.74 seconds
2023-May-19 00:10:17: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:18: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:18: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:18: **GPU4 DAG** generation will take longer, please wait...
2023-May-19 00:10:18: New job from etchash.auto.nicehash.com:9200
2023-May-19 00:10:18: **GPU0:** 3359 MB DAG generated in 6.36 seconds
2023-May-19 00:10:19: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:19: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:20: New job from kheavyhash.eu.mine.zergpool.com:5555
2023-May-19 00:10:20: New job from kheavyhash.eu.mine.zergpool.com:5555

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by UselessGuru** [comment]
Any news?

**Comment by Grumpy-Dwarf** [comment]
This option works for each algorithm/coin separately. In your command line one device is selected only for Kaspa. In order to set device 1 for all algorithms, the -devices 1 option must be written after each algorithm declaration.

In your case it will be the following command line:
```NanoMiner-v3.8.1\nanominer.exe -algo Etchash -devices 1 -pool1 etchash.auto.nicehash.com:9200 -useSSL false -wallet ################################ -rigName '##############' -rigPassword x -algo Kaspa -pool1 kheavyhash.eu.mine.zergpool.com:5555 -useSSL false -wallet ##################### -rigName '##################' -rigPassword c=BTC,ID=#########,pl=0 -mport 0 -webPort 4001 -checkForUpdates false -noLog true -watchdog false -devices 1```
