### ISSUE TITLE
No device detected on nanominer  grin mining after hardfork

### ISSUE THREAD

**Issue by rrahul9637** [nanopool/nanominer#39]
i use nvidia gtx 1060. miner is not detecting any device. it is working fine with bminer

any help?

**Comment by Grumpy-Dwarf** [comment]
Isn't it same issue as #36 ?
Do you have up-to-data Nvidia driver?

**Comment by Grumpy-Dwarf** [comment]
We now print warning message in case Nvidia driver version is insufficient since release 1.5.3. Feel free to reopen the issue if GPUs are not detected with recent Nvidia driver.
