### ISSUE TITLE
Problem with wallet

### ISSUE THREAD

**Issue by CiobiStar** [nanopool/nanominer#4]
I have a small problem.I made a new eth wallet and i introduced to my config,but when minning is on,i dont recive any money.0 shares every time..
My config is: 
; nanominer.exe config.ini
[CryptoNightv8]
wallet = 0*****5277746ec424787be520c4758********
rigName = ciobi
email = zeulapolo@gmail.com
pool1 = xmr-eu1.nanopool.org:14433
pool2 = xmr-eu2.nanopool.org:14433
pool3 = xmr-us-east1.nanopool.org:14433
pool4 = xmr-us-west1.nanopool.org:14433
pool5 = xmr-asia1.nanopool.org:14433

**Comment by Grumpy-Dwarf** [comment]
What hashrate do you have? With 1000 H/s for example you should have a share every two minutes in average on nanopool.

**Comment by CiobiStar** [comment]
> What hashrate do you have? With 1000 H/s for example you should have a share every two minutes in average on nanopool.

I have just 800

**Comment by Grumpy-Dwarf** [comment]
And still no shares? That's weird. Please check miner log - what are total shares and rejected shares numbers after some mining? If miner log shows any shares next step is to find you account on nanopool. It should appear in ten minutes in case at least single share was sent.

**Comment by CiobiStar** [comment]
> And still no shares? That's weird. Please check miner log - what are total shares and rejected shares numbers after some mining? If miner log shows any shares next step is to find you account on nanopool. It should appear in ten minutes in case at least single share was sent.

Nop.I tried also with ethereum classic and i still got 0 shares.I don;t know why

**Comment by Grumpy-Dwarf** [comment]
Just noticed pools were the XMR ones, looks like configuration problem.
