### ISSUE TITLE
HiveOS NanoMiner XMR CPU ExitCode 1.

### ISSUE THREAD

**Issue by YeetTeamYT** [nanopool/nanominer#407]
Im trying to mine XMR on Hive OS with NanoMiner but it keeps giving me the error ExitCode 1. The CPU is at 25-50C (outside is 0C, thats why so low temps) But it says waiting to cool down. i dont know why, but id like to mine.
Thx in advance. :)
Note - Ive added a screen shot if needed :)
![Screenshot_28](https://github.com/nanopool/nanominer/assets/96380370/b106b8cf-c52b-4e7d-b5b9-b97a79ce83e4)

**Comment by FibreFoX** [comment]
Probably related to #405 due to Nanominer (even though it was not written in the changes) seemingly to require a more modern OS/more modern glibc.

What version of Nanominer are you using?

**Comment by YeetTeamYT** [comment]
> Probably related to #405 due to Nanominer (even though it was not written in the changes) seemingly to require a more modern OS/more modern glibc.
> 
> What version of Nanominer are you using?

I don't know the nanominer version, all I know is that it's the latest version of HIVE OS.

**Comment by FibreFoX** [comment]
Quoting https://hiveon.com/knowledge-base/guides/what_is_hive/
```
Hiveon OS is an operating system developed on the basis of Linux distribution Ubuntu 16.04 LTS.
```

But looking into https://download.hiveos.farm/VERSIONS.txt that `U 18.04` probably means "Ubuntu 18.04"

Both versions are "too old" for the new Nanominer, try the previous [v3.8.5](https://github.com/nanopool/nanominer/releases/tag/v3.8.5)

**Comment by YeetTeamYT** [comment]
> Quoting https://hiveon.com/knowledge-base/guides/what_is_hive/
> 
> ```
> Hiveon OS is an operating system developed on the basis of Linux distribution Ubuntu 16.04 LTS.
> ```
> 
> But looking into https://download.hiveos.farm/VERSIONS.txt that `U 18.04` probably means "Ubuntu 18.04"
> 
> Both versions are "too old" for the new Nanominer, try the previous [v3.8.5](https://github.com/nanopool/nanominer/releases/tag/v3.8.5)

Working On It!

**Comment by FibreFoX** [comment]
@YeetTeamYT :) in that case you might want to close this issue
