### ISSUE TITLE
Mining XMR, Running only 8 Minutes on ubuntu

### ISSUE THREAD

**Issue by WilliWardany** [nanopool/nanominer#411]
I use nanominer on my ubuntu os, running the nonominer with Script. 

./nanominer -algo randomx -wallet aaaaaaaaaaaaaaaazzzzzzzzzzzzzzzzzzzzzzzzzz -coin xmr -rigName Milli1 -email  myemail -cpuThreads 4 -watchdog false

but mining only work 8 minutes and suddenly stop without warning.

![image](https://github.com/nanopool/nanominer/assets/60079807/72f9f172-5845-4176-887b-b399d23ec61d)

**Comment by Grumpy-Dwarf** [comment]
Fixed in version 3.8.10
