### ISSUE TITLE
FEATURE request - disable random workername generation

### ISSUE THREAD

**Issue by S74nk0** [nanopool/nanominer#43]
Hello,

NanoMiner seems to generate a random worker-name if none is provided. This causes issues for NiceHash Miner as this will generate unmanaged rigs on every switch.

![image](https://user-images.githubusercontent.com/1517233/63350561-ef8ed180-c35d-11e9-88c9-09e9c3c39880.png)

Can you please provide a build where worker-name is left blank or provide instructions how to disable worker-name if possible. 

This is how it looks.
![image](https://user-images.githubusercontent.com/1517233/63351173-071a8a00-c35f-11e9-9c7a-feefd91ea608.png)

The miner sends `{"id": 2, "method": "mining.authorize", "params": ["3JonGfe39jJtHGuehvcNTUcAFudKb7CHoa$0-mFJc0D-2hVy92ziBu9n5YA.Bashful_492e8028","x"]}`

And this will not work because the first parameter cannot be parsed. 
We support `BTC`, `BTC.workername` (for external miners) and `BTC$RigID` (when running via nhm).

**Comment by Grumpy-Dwarf** [comment]
We actually have feature of disabling rig name generation. It can be set empty by
`rigName=`
line. Unfortunately this feature was not documented. So thanks for pointing out. Please report if this resolves the issue.

**Comment by S74nk0** [comment]
@Grumpy-Dwarf this indeed sets workername to be empty. Thanks for pointing it out. We will update our plugin. 

Closing issue [solution in comment](https://github.com/nanopool/nanominer/issues/43#issuecomment-524275282).
