### ISSUE TITLE
Bluescreen after Connection Losses

### ISSUE THREAD

**Issue by TheShaman** [nanopool/nanominer#44]
Starting with 1.5x I have been dealing with a very annoying behavior when mining ETH:

When miner loses connection to the pool (3rd world Internet, so that happens quite often) mining is suspended as it is supposed to, but as soon as the connection comes back up and mining should resume (it did in older versions) I get instant Windows BSOD, telling me that memory management unfortunately ran into a problem, yaddayadda, reboot. 

Windows 10, 17134
AMD RX580 with latest stable driver

Anything I can do about that on my end except going back to an older version of the miner?

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting. I guess it's because of memory tweak. Does disabling AMD memory timings with `memTweak=0` in config.ini fixes latest releases of miner?

**Comment by TheShaman** [comment]
Thanks Grumpy! Will give that a try, would make sense to a certain extent (I did not have that flag disabled, strange though that it starts mining fine and only crashes after the first disconnect when it comes online again...)

Will test and report back in a day or two!

**Comment by TheShaman** [comment]
Update: adding `memTweak=0` to the config seems to do the trick. 

I pulled the Ethernet cable a couple times for a while, simulating what our crappy backbone providers frequently do to us, and: mining resumes after reconnect with no crashes or BSODs. 
Marginally lower hashrate, but I can live with that. 

Thanks for the workaround!

**Comment by Grumpy-Dwarf** [comment]
This should have been fixed with recent nanominer update.

**Comment by Grumpy-Dwarf** [comment]
Feel free to reopen the issue if you observe the same behavior.
