### ISSUE TITLE
Autoupdate seems to hate slow connections

### ISSUE THREAD

**Issue by TheShaman** [nanopool/nanominer#45]
One of the features I really liked to see was the ability to have the miner automatically check for updates on start and update itself if instructed to do so. 

However, it does not work here. ;)

Every time it finds an update it says that it is downloading it, then, shortly after, reports a timeout error for the download and just keeps mining. 

Seems like it either expects the download to finish in about 30 seconds (won't happen for the majority of the world population with connections of 1 MBit or less), or it is extremely fickle about transfer rate drops  / occasional packet loss and does not resume downloads.

**Comment by Grumpy-Dwarf** [comment]
Please check if version 1.6.0 updates to 1.6.1. Some changes were made in it.
