### ISSUE TITLE
mport doesn't work

### ISSUE THREAD

**Issue by cires316** [nanopool/nanominer#47]
what am i doing wrong when trying to use the mport. I have 2 instances of nanominer running and the second one never works because it can't bind the port on 3333

the docs say to use -mport -3334 or whatever port i want to use but it never seems to take. Also does not seem to work if I put it in the config.ini file?

**Comment by Grumpy-Dwarf** [comment]
Please note `mport` is common parameter. Must be specified outside of algorithm section. Just checked the following config files and both work with nanominer 1.6.1:
```ini
mport=3334
[ethash]
wallet=0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5
```
Without algorithm section (algorithm is auto-discovered for ETH):
```ini
mport=3334
coin=eth
wallet=0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5
```

Several instances of miner run even if Ethman monitoring port is occupied.
