### ISSUE TITLE
Can I get the dual claymore miner

### ISSUE THREAD

**Issue by KillerPriest86** [nanopool/nanominer#48]
Just getting back into mining. I use to get a better hashrate on claymore at 17mh's now I'm stuck with only getting 4mh's is there a version I can get? Been looking for it to no avail..

**Comment by Grumpy-Dwarf** [comment]
I guess you have some AMD GPUs, need to [enable compute mode](https://www.amd.com/ru/support/kb/faq/dh-024).

**Comment by KillerPriest86** [comment]
No  I have a 970 geforce.

**Comment by KillerPriest86** [comment]
I have put it on through nvidia control panel it hasn't helped.

**Comment by Grumpy-Dwarf** [comment]
Looks like your card have 4 GB onboard memory. Is is not enough for ETC on windows 10 for DAG to fit into it. You can either mine different Ethash coins with smaller DAG either use Windows 7 or Linux.
Do you use nanominer of Claymore's dual miner?

**Comment by KillerPriest86** [comment]
I'm using nanominer. I tried running claymore and ethminer, but they won't even use my 970 now. I guess it's something to do with dag increase maybe?

**Comment by Grumpy-Dwarf** [comment]
I'm almost sure it is related to DAG size. As I've written before, options to increase the hashrate are using Windows 7 or Linux or mining coins with smaller DAG size like Ubiq or Metaverse or any other Ethash coin from whattomine.com. All Ethash coins have DAG size smaller than ETC and ETH have.

**Comment by KillerPriest86** [comment]
Do you think switching to a linux base system would help improve performance by chance?

**Comment by Grumpy-Dwarf** [comment]
I'm sure it will. 4 GB your GPU has is enough for 3.4 GB ETH DAG but unfortunately Windows 10 consumes some video memory from each GPU.

**Comment by KillerPriest86** [comment]
Yeah thats what I read. Well thanks for the assistance.
