### ISSUE TITLE
testing randomx api results

### ISSUE THREAD

**Issue by vanities** [nanopool/nanominer#49]
When trying to test the api results of Radnomx, I'm getting:

`Error: EthMan: error parsing JSON: invalid character 'G' looking for beginning of value`

I'd like to test the API of what randomX will return, but I'm not sure how to set it up correctly,

>config.ini
```
[RandomX]
wallet=my_address
#pool1=randomx-benchmark.xmrig.com:7777
```

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting. Had a bug but now setting RandomX algorithm works both on Nanopool and randomx-benchmark.xmrig.com with  [release 1.6.2](https://github.com/nanopool/nanominer/releases/tag/v1.6.2).
As for EthMan API - it works from the EthMan program itself. For checking stats from browser better look at our native [BoringAPI](https://github.com/nanopool/BoringAPI): http://127.0.0.1:9090/stats
Have also a nice web interface with hashrate plots for the last three hours: http://127.0.0.1:9090

**Comment by vanities** [comment]
Grumpy- 
I was hitting the wrong port, lol (3333, not 9090) so that was my bad.

Thanks for fixing this so quickly!
