### ISSUE TITLE
RandomX OpenCL/CUDA

### ISSUE THREAD

**Issue by vanities** [nanopool/nanominer#51]
Are there plans to implement an OpenCL/CUDA for randomX? We would like to keep nanominer as our main miner, we have amd cards in our machines. Xmrig just announced their combined cpu and gpu miner.

Thanks!

**Comment by Grumpy-Dwarf** [comment]
It's rather complicated, not sure if we will ever support RandomX on GPUs. Let's keep this issue opened as a feature request for RandomX till we see the mining market after Monero hardfork and make final decision.

**Comment by Grumpy-Dwarf** [comment]
We've analyzed the algorithm and decided to leave RandomX CPU-only in nanominer.
