### ISSUE TITLE
Feature request: Set custom GPU % usage

### ISSUE THREAD

**Issue by Tomeo213** [nanopool/nanominer#52]
Could you please add something like this into the miner?
I used to mine iwth claymore, but since claymore does not work on my gpu now, Im searching a miner with such an option with no luck.

**Comment by Grumpy-Dwarf** [comment]
It's rather complicated for us since we try to support several algorithms, not Ethash only and can't spend resources on this feature for each of algorithms. I'm afraid it won't be implemented in the nearest future unless lots of users want this to be implemented.
