### ISSUE TITLE
Not getting paid with Monero

### ISSUE THREAD

**Issue by camelCaseCo** [nanopool/nanominer#53]
I am new to mining and just set up Nanominer. It is on my personal laptop, so I only get 400-500 H/s (slow, I know) It says that I am getting shares, but I don't have any Monero in my wallet. 
Here is my config.ini:
```
[RandomX]
coin = XMR
wallet = 4BEHPhzTWqqeorVVSsBaCo6Z2D2KvY16xd4Roi7nvyjVWBpmZwMdCRejFm1bHovR2zbvL424LFLC1DDP2UpVPc7W7jGJPbf
cpuThreads = 4
email = ***********@gmail.com
```
Thanks a lot!

**Comment by Grumpy-Dwarf** [comment]
Hello @camelCaseCo , sorry for delay.
As you can see on your [account page ](https://xmr.nanopool.org/account/4BEHPhzTWqqeorVVSsBaCo6Z2D2KvY16xd4Roi7nvyjVWBpmZwMdCRejFm1bHovR2zbvL424LFLC1DDP2UpVPc7W7jGJPbf) you have 0.00121110 XMR. Your minimum payout limit is currently configured to default 1 XMR so only 0.12% of it is reached.
Payout limit can be configured to any value between 0.1 and 10 XMR.
Pool sends XMR to your wallet after reaching payout limit.
