### ISSUE TITLE
The NVIDIA card pulls down nanominer v1.6.2

### ISSUE THREAD

**Issue by Thorgrlm** [nanopool/nanominer#55]
Hi all, my machin work with Ubuntu 18.04 and have a thre cards AMD RX580 and one NVIDIA 1050ti
The problem what I've is  with the NVIDIA card, sometime it disconnect.
 If I configure the nanominer for work  with AMD and NVIDIA together cards, NVIDIA card pulls down the nanominer and it stop to work, if I run a two nanominer, one with AMD and other with NVIDIA, the AMD cards with nanominer work fine, but the nanominer with NVIDIA cards work intermittent
When I do work NVIDIA card with t-rex to extrac ravencoin, all work fine but with ethereum and nanominer I have this problem.
someone can help my?
Thanks

**Comment by Grumpy-Dwarf** [comment]
As far as I remember the problem has already been discussed on Discord. It is related to workers with lower hashrate are not observed on pool in case no shares were sent in twenty minutes. So closing this issue now.

**Comment by Thorgrlm** [comment]
ok, it's true, thanks you
