### ISSUE TITLE
Running as root crashed the miner then the os

### ISSUE THREAD

**Issue by nicolaevladescu** [nanopool/nanominer#58]
Saw this `Hint: launch the miner using root privileges to get a better hashrate.`

Followed the on screen suggestion, ran with sudo computer froze then i got `Bus error` even when running without root then i couldn't even reboot because of lots of errors pointing to `/dev/` devices, had to shutdown physically.

I am using ubuntu 18.04 and 6 amd gpus

**Comment by Grumpy-Dwarf** [comment]
That's probably because of memory tweaks applied when running as root. If default memory tweak crashes your system you can either add `memTweak=0` to common options either run miner as user and ignore the hint.
