### ISSUE TITLE
RT 5500 XT not recognised

### ISSUE THREAD

**Issue by image28** [nanopool/nanominer#59]
Not sure if this has been reported yet. Logs bellow in case it hasn't

[log_2020-01-16_09-32-28.log](https://github.com/nanopool/nanominer/files/4067420/log_2020-01-16_09-32-28.log)

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting. Will release update soon thanks to your log with those binaries included.

**Comment by Grumpy-Dwarf** [comment]
Please check if [version 1.7.1](https://github.com/nanopool/nanominer/releases/tag/v1.7.1) just released works with your 5500.
