### ISSUE TITLE
Can't mine XMR with CPU 

### ISSUE THREAD

**Issue by xq0404** [nanopool/nanominer#6]
I have an AMD Threadripper 2950X CPU and an RX 480 GPU, but my CPU is not recognized while mining Monero.

**Comment by Grumpy-Dwarf** [comment]
We only support RandomHash (PascalCoin) mining on CPU. Current nanominer releases can mine Monero with Nvidia and AMD GPUs but not with CPUs.

**Comment by xq0404** [comment]
Thank you.
