### ISSUE TITLE
Driver not found

### ISSUE THREAD

**Issue by meeeeeeeeeeee** [nanopool/nanominer#60]
![lol no working](https://user-images.githubusercontent.com/16529999/72494960-bb232280-37e2-11ea-986c-5ad81b46beaf.PNG)

every time i try to start this error pops up?

**Comment by Grumpy-Dwarf** [comment]
What GPU cards do you have?

**Comment by meeeeeeeeeeee** [comment]
I have 2 AMD Radeon HD 6870

**Comment by Grumpy-Dwarf** [comment]
I'm afraid those GPUs have TeraScale 2 architecture which is no longer supported by recent AMD drivers. Nanominer only supports AMD cards of newer GCN and RDNA architectures.
You can't mine any Ethash coin on it anyway since it has one GB memory and minimum DAG size necessary for Ethash is one GB.
