### ISSUE TITLE
Can the RandomX be executed on a cloud server？

### ISSUE THREAD

**Issue by zhaoran025** [nanopool/nanominer#61]
config_xmr  file:
`
[RandomX]
; Address to send funds to.
wallet = ************

; (Optional) Coin to mine.
coin = XMR

; (Optional) Rig (worker) name.
rigName = worker

email = ****@qq.com

pool1 = xmr-jp1.nanopool.org:14444
`
Result:
`
2020-01-17 16:37:10: <info> Log is written to file
2020-01-17 16:37:10: <info> GPU watchdog is enabled
2020-01-17 16:37:10: <info> Never calling reboot.sh (always restarting the miner in case of errors). 
2020-01-17 16:37:10: <info>  Setting up algorithm: RandomX
2020-01-17 16:37:11: <info>  Connecting to pools...
2020-01-17 16:37:13: <info>  Connected to pool: xmr-jp1.nanopool.org:14444
2020-01-17 16:37:14: <info> CPU: Intel(R) Xeon(R) CPU E5-26xx v4 | AVX2: yes | SSSE3: yes | AES: yes
2020-01-17 16:37:14: <info>  New job from xmr-jp1.nanopool.org:14444 | share difficulty = 480 kH
2020-01-17 16:37:14: [Statistics] Monero - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:03
2020-01-17 16:37:14: <info>  Updating dataset...
`
Why is my cpu usage rate 0? Is the program wrong? I am executing the program on the cloud server

**Comment by Grumpy-Dwarf** [comment]
Please wait for several minutes for miner to update dataset and receive some tasks from pool to see the hashrate.

**Comment by zhaoran025** [comment]
But I didn't find it in the process

**Comment by zhaoran025** [comment]
top result
`  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                  
 1628 root      20   0  609120  11404   1768 S   2.0  0.3 310:34.39 barad_agent                                                                                                                                                                                              
29275 root      20   0 1300788 114920   8408 S   1.0  3.0 264:00.77 node /usr/local                                                                                                                                                                                          
    9 root      20   0       0      0      0 S   0.3  0.0  11:50.02 rcu_sched                                                                                                                                                                                                
 1042 mysql     20   0 1904256 631284  11392 S   0.3 16.3 360:15.77 mysqld                                                                                                                                                                                                   
 1627 root      20   0  183820   9424   1992 S   0.3  0.2  57:30.44 barad_agent                                                                                                                                                                                              
18533 mongod    20   0  492608 154380   5640 S   0.3  4.0 271:46.51 mongod                                                                                                                                                                                                   
27864 root      20   0  341884 204724   3872 S   0.3  5.3  22:42.62 YDService                                                                                                                                                                                                
    1 root      20   0  190956   3660   2272 S   0.0  0.1  11:54.34 systemd                                                                                                                                                                                                  
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.59 kthreadd `

**Comment by kosukekurimoto** [comment]
kernel: [55461.127089] nanominer[21538]: segfault at 40ffffc0 ip 00007f15e44ff01c sp 00007f15c77fda90 error 6

**Comment by bdelgado1995** [comment]
I'm seeing this issue too on an Azure cloud VM (Ubuntu 18.04.5 LTS). the problem is that the program seg faults just after it says "2021-02-19 08:39:34: Updating dataset..."

In case it matters, I have 16GB free on the disk. CPU:  Intel(R) Xeon(R) CPU E5-2673 v4

dmesg:
[11725461.269271] nanominer[4840]: segfault at 0 ip 00007fafaf55101c sp 00007faf88ff8a70 error 6
[11725461.269275] Code: 90 90 90 90 90 90 90 90 90 90 90 90 90 90 53 55 41 54 41 55 41 56 41 57 48 8b 3f 48 89 d5 51 0f 0d 0e 48 89 eb e8 e4 2f 00 00 <4c> 89 06 4c 89 4e 08 4c 89 56 10 4c 89 5e 18 4c 89 66 20 4c 89 6e
