### ISSUE TITLE
Failed to verify ssl certificate against host

### ISSUE THREAD

**Issue by aptpupil303** [nanopool/nanominer#62]
The system was working well then it just stopped and started producing the error unable to verify ssl certificate against host.  Lasted a few minutes but corrected itself.  This is on version 1.7.1

**Comment by Grumpy-Dwarf** [comment]
Used to reproduce such a behavior while dev fee mining on some connections. It is likely fixed in [nanominer 1.8.2](https://github.com/nanopool/nanominer/releases/tag/v1.8.2) just released. Feel free to reopen the issue if still observe such a behavior.
