### ISSUE TITLE
1.7.2: config files are ignored - always mining to PASC address with name BIG_FARM

### ISSUE THREAD

**Issue by mmattl** [nanopool/nanominer#63]
This is a heavy issue.
Even if you choose another currency, the PASC mining is always added automatically (part of binary)

**Comment by Grumpy-Dwarf** [comment]
OMG, this is critical.

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting, removed 1.7.2  binaries. Will be fixed in next release.

**Comment by mmattl** [comment]
Ok - great . Thank you!

**Comment by Grumpy-Dwarf** [comment]
Please check updated 1.7.3 release, seems to be fixed there.

**Comment by mmattl** [comment]
yes it is - resolved in 1.7.3
