### ISSUE TITLE
1.7.1 gfx1010 hang up

### ISSUE THREAD

**Issue by mfu-mcosys** [nanopool/nanominer#64]
It seems like something goes wrong with a amd rx5700.
After some time (few mins) without problems a random gfx1010 hangs up with eth

`2020-01-24 21:14:16: [Statistics] Ethereum last 10 min - GPU 0: 50.429 MH/s, GPU 1: 50.430 MH/s, GPU 2: 48.223 MH/s, GPU 3: 48.233 MH/s, GPU 4: 48.219 MH/s, GPU 5: 48.203 MH/s, GPU 6: 50.430 MH/s, GPU 7: 48.241 MH/s, GPU 8: 48.221 MH/s, GPU 9: 35.868 MH/s, GPU 10: 32.575 MH/s, GPU 11: 50.430 MH/s. Total: 559.500 MH/s.
2020-01-24 21:14:34: <warning>  GPU 3 hung up
2020-01-24 21:14:34: <info>  Miner has not been restarted before
2020-01-24 21:14:34: <info>  Self-restarting miner process.
`

DMESG:
`
[ 1507.095911] gmc_v10_0_process_interrupt: 10 callbacks suppressed
[ 1507.095923] amdgpu 0000:0b:00.0: [gfxhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process nanominer pid 2288 thread nanominer pid 2424)
[ 1507.096104] amdgpu 0000:0b:00.0:   in page starting at address 0x00000006c899b000 from client 27
[ 1507.096205] amdgpu 0000:0b:00.0: GCVM_L2_PROTECTION_FAULT_STATUS:0x00101030
[ 1507.096287] amdgpu 0000:0b:00.0: 	 MORE_FAULTS: 0x0
[ 1507.096346] amdgpu 0000:0b:00.0: 	 WALKER_ERROR: 0x0
[ 1507.096406] amdgpu 0000:0b:00.0: 	 PERMISSION_FAULTS: 0x3
[ 1507.096470] amdgpu 0000:0b:00.0: 	 MAPPING_ERROR: 0x0
[ 1507.096531] amdgpu 0000:0b:00.0: 	 RW: 0x0
`
I dont know if its a hardware problem...but ethminer works nice (1hour+).

memTweak=0 was added in the config.ini

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting, did not test RX 5700 on Linux much, last time I tried they did not work at all in Linux. Will try with updated drivers.

**Comment by mfu-mcosys** [comment]
Something new: it works without mixing cuda+opencl, if i start nanominer just with all nvidia (cuda) cards it works, if i start nanominer jsut with all amd (opencl) cards, it works. (tested on win10).

**Comment by martinberlin** [comment]
Any news on this? Did someone got it working. 
I get an error message that restarts and that I have to increase netTweak

**Comment by Grumpy-Dwarf** [comment]
This was reproduced on amdgpu-pro 20.40 Linux driver. Will recheck on latest 20.45 too now.

**Comment by Grumpy-Dwarf** [comment]
On 20.45 it does not hang but crashes inside driver with same messages in kernel log and terminates.

**Comment by Grumpy-Dwarf** [comment]
I'm negatively impressed with 20.45 quality. First time I've ever seen my 5700 xt at 98 degrees with default fan settings.

**Comment by Grumpy-Dwarf** [comment]
Fixed in [nanominer 3.1.4](https://github.com/nanopool/nanominer/releases/tag/v3.1.4)
