### ISSUE TITLE
Nanominer causes PC freeze/crash when attempting CPU and GPU mining

### ISSUE THREAD

**Issue by djjkn** [nanopool/nanominer#66]
I have been mining on my GPU on nanominer for a while with little to no issues. However, when I try to mine with CPU and GPU simultaneously the screen on my PC freezes. Sometimes I am able to Ctrl+Alt+Delete and it fixes itself, but later it will freeze and I will have to manually shut down the PC. 

System Specs: 
Ryzen R5 1600 
RX 5700 flashed with RX 5700 XT bios
Windows 10 
Nanominer 1.7.3

Here is my config: 

autoUpdate=true

[Ethash]
wallet=xxx
coin=ETH

email = xxx

[RandomX]
wallet = xxx
email = xxx

pool1 = xmr-us-east1.nanopool.org:14433
pool2 = xmr-us-west1.nanopool.org:14433
pool3 = xmr-eu1.nanopool.org:14433
pool4 = xmr-eu2.nanopool.org:14433
pool5 = xmr-asia1.nanopool.org:14433

**Comment by imrecsoka** [comment]
9 days ago, nobody has replied.
Anyways i want to know , i never knew Pascal can be mined on a GPU, i mean now with the fork?
Is it worth while trying to mine with an RX 470 card?

**Comment by Grumpy-Dwarf** [comment]
Sorry for long delay.
Pascal is miner on CPU in nanominer. There is no public GPU miner for it's RandomHash2 algorithm as far as I know.

As for system freeze - could you please specify number of threads for RandomX equal to number of CPU cores - 1? This is done by adding `cputhreads=5` for your 6 cores CPU to RandomX section. This will leave single CPU execution thread idle to service GPUs.

**Comment by djjkn** [comment]
> Sorry for long delay.
> Pascal is miner on CPU in nanominer. There is no public GPU miner for it's RandomHash2 algorithm as far as I know.
> 
> As for system freeze - could you please specify number of threads for RandomX equal to number of CPU cores - 1? This is done by adding `cputhreads=5` for your 6 cores CPU to RandomX section. This will leave single CPU execution thread idle to service GPUs.

Reducing my CPU cores fixed the issue, thank you!
