### ISSUE TITLE
Solo Mining - confirmation please

### ISSUE THREAD

**Issue by imrecsoka** [nanopool/nanominer#68]
Hi,

I have edited the config file and ommited the pool i was using as well as the web-login.worker password information using ";" at the beginning of the line.

As per the readme guide:

"To mine Pascal in a solo mode please provide ip and port of Pascal full node Wallet software. The wallet number filled in config does not matter in such case. Block payload would be "Miner Name" set up in Pascal full node Wallet followed by nanominer version. Example of a file for solo mining Pascal using local wallet software:

wallet = 0
pool1 = 127.0.0.1:4009

I now have this in my config file:

![image](https://user-images.githubusercontent.com/25494601/74102892-91131500-4b82-11ea-8e3c-a663bcb70dca.png)

I have my pascal wallet open and i started the nanominer batch file to call nanominer {config_file} : 
Does this look kosher?  how do i know if i am mining solo ?

![image](https://user-images.githubusercontent.com/25494601/74102984-41811900-4b83-11ea-81f4-ce3f5bf67bc2.png)

Thank you in advance

**Comment by Grumpy-Dwarf** [comment]
You can see in wallet window "Miner Clients: 1 connected JSON-RPC clients" - this is your miner connected.
If you see up-to-date in wallet's block explorer tab and miner is connected with a stable hashrate this means everything looks fine.

**Comment by imrecsoka** [comment]
Hi,
"...and miner is connected with a stable hashrate...."
Is this in the Nanominer itself? hashrate says 219 kh/s roughly 
"... and new jobs arriving from time to time this means everything looks fine."
Is this also in the Nanominer  window ...it basically says "new job from....127.0.0.1:4009" ?

Right ?

**Comment by Grumpy-Dwarf** [comment]
Yes, everything is right.

**Comment by imrecsoka** [comment]
Thank you Grmpy-Dwarf

One thing i just want to check , is what the heck is this Payload or Name or whatever the hell it is called...
what is the purpose of it , or functon, and is it required?
I really dont understand , and the guide or help does not give enough information around this.

**Comment by Grumpy-Dwarf** [comment]
That's what you see in blocks explorer "Miner Payload" string. Can be set up in wallet: Project->Options->Miner name. Pools set up their names usually. Nanominer adds /nanominer _version_ to configured miner payload.

If in doubt, you can check mining on [testnet wallet](https://github.com/PascalCoin/PascalCoin/releases/tag/TESTNET_5.2) - blocks are much simpler there. However, those pascals are not real mainnet pascals, just testing coins.

**Comment by imrecsoka** [comment]
Tried to follow that link, but i dont understand what i must do, download the test 5.2 zip?
I am still under i underthrne this string identifier if u call it this?
I am just trying to clarify if i need this?
Do u plug the name in the wallet? and then the same name in the miner program like RHMiner and anominer? 
If you can have a session with me or if u can just share me a screenshot?
The thing is, do  need to bother with it?
My miner seems to be mining solo, so it should be fine right?
