### ISSUE TITLE
AMD’s Radeon VII is not recognized when mining Monero

### ISSUE THREAD

**Issue by xq0404** [nanopool/nanominer#7]
It seems the latest GPU from AMD, Radeon VII, is not recognized by Nanominer while XMR is being mined.  The same is not true of Ethereum. Both Radeon VII and RX 480 are recognized and both can mine ETH simultaneously. 

64-bit Windows 10

**Comment by Grumpy-Dwarf** [comment]
Thanks for reporting, will fix with next upcoming AMD Monero algorithm update.

**Comment by xq0404** [comment]
> 
> 
> Thanks for reporting, will fix with next upcoming AMD Monero algorithm update.

Thank you and really appreciate it.

**Comment by Grumpy-Dwarf** [comment]
[Nanominer 1.3.0](https://github.com/nanopool/nanominer/releases/tag/v1.3.0) has just been released which supports Monero on AMD cards.
