### ISSUE TITLE
No GPU devices found were detected, exiting. (AMD RX570, Arch Linux)

### ISSUE THREAD

**Issue by quisys** [nanopool/nanominer#72]
[nanominer output](https://pastebin.com/svuC4dbM)

[clinfo output](https://pastebin.com/RpwX3cZa)

any further detailed required will be provided asap

**Comment by quisys** [comment]
I'm also on the latest version, cleanly built with `opencl-amdgpu-pro-dev` installed

**Comment by Grumpy-Dwarf** [comment]
Looks like you have Clover OpenCL. Nanominer only supports AMDGPU-pro OpenCL which has `AMD Accelerated Parallel Processing` platform name and `Advanced Micro Devices, Inc.` platform vendor. We could support other OpenCL platforms for AMD cards too but looks like they are not maintained well.
Try installing `opencl-amdgpu-pro-pal` or `opencl-amdgpu-pro-orca`.

**Comment by markusbrovold** [comment]
I have this issue on a laptop, it works for a while but then suddently it fails with this message. Geforce GTX1050ti 4GB, win10

**Comment by megamanzerobasslink** [comment]
arch is a meme :)

**Comment by Grumpy-Dwarf** [comment]
> I have this issue on a laptop, it works for a while but then suddently it fails with this message. Geforce GTX1050ti 4GB, win10

Maybe laptop disables discrete GPU to save power. You can check if driver sees the Nvidia GPUs by running `nvidia-smi` command line tool (is is located in `C:\Program Files\NVIDIA Corporation\NVSMI`)
If it doesn't see GPUs at the moment miner doesn't see them - there is nothing we can do inside miner.
