### ISSUE TITLE
Video Memory usage only about 60%

### ISSUE THREAD

**Issue by Toni19944** [nanopool/nanominer#73]
Hey there, I could use a quick help for finding a parameter to utilize my GPU's fully when only mining, currently both of my rigs seem to only be using around 60% or video memory by the miner. Nvidia Pascal GPU's in both rigs.
Or does it even matter? or on other words is it normal? So right now other rig uses 3,8GB of a 6GB card, and other one is using 4,4GB of a 8GB card.

I would really appreciate some help with this since I'm a total noob at what I'm doing and don't really want to go and break the miner by screwing around too much

**Comment by Grumpy-Dwarf** [comment]
This is absolutely normal, miner does not need more than 4 GB of memory on GPUs for ETH/ETC. It only uses what it needs from the total amount of memory. The performance is limited by memory access speed, not memory size in Ethash, for 6 and 8 GB cards at least.
