### ISSUE TITLE
Web interface does not work when nanominer is started as a system service on Ubuntu

### ISSUE THREAD

**Issue by r2DoesInc** [nanopool/nanominer#79]
Ubuntu 20.20
nanominer-linux-1.9.5

Web interface works when i start the miner manually
When using the following startup script, the web interface fails to load with a `404 - Cannot open requested path`

```
[Unit]
Description=Start miner

[Service]
ExecStart=/home/nanominer-linux-1.9.5/nanominer /home/nanominer-linux-1.9.5/config.ini
ExecStop=/usr/bin/pgrep nanominer | /usr/bin/xargs kill

Restart=always

[Install]
WantedBy=default.target
```

**Comment by Grumpy-Dwarf** [comment]
It expects `web` folder in current directory in order to work. I'm almost sure additional
```ini
WorkingDirectory=/home/nanominer-linux-1.9.5
```
line will fix it.

**Comment by r2DoesInc** [comment]
That did it. I assumed it was due to a path related issue, but i did not see that `workingDirectory` config option anywhere. Perhaps the instructions should be updated with this information as i doubt I am the only one using a service to run the miner.

Thanks again!

**Comment by r2DoesInc** [comment]
Just tested this and I see no change. 

config is

```
[ethash]
wallet=xxxxxx
coin=eth
rigName=xxxxx
email=xxxxxx
webPassword=xxxxxx
logPath=/home/nanominer-linux-1.9.5/logs/
workingDirectory=/home/nanominer-linux-1.9.5/
```

**Comment by Grumpy-Dwarf** [comment]
I mean systemd [WorkingDirectory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=) actually, sorry for confusion.

**Comment by jrblanno** [comment]
did it work for you , @r2DoesInc ? could you post your config, please ?

**Comment by jorijnsmit** [comment]
I can confirm that the web interface works after adding `WorkingDirectory` (indeed `nanominer` looks for `./web`).

Also the stop command gave my some troubles, so changed it. My full `/etc/systemd/system/nanominer.service`:

```
[Unit]
Description=Nanominer

[Service]
WorkingDirectory=/home/gosuto/nanominer
ExecStart=/home/gosuto/nanominer/nanominer /home/gosuto/nanominer/config.ini
ExecStop=/usr/bin/pkill -f nanominer
Restart=always
RestartSec=3
	
[Install]
WantedBy=multi-user.target
```
`sudo systemctl daemon-reload; systemctl restart nanominer`
