### ISSUE TITLE
nocolor

### ISSUE THREAD

**Issue by toptim** [nanopool/nanominer#8]
please add nocolor = true option

**Comment by Grumpy-Dwarf** [comment]
Are there any technical motivation for console log without color? Don't you like nanominer default color scheme?

**Comment by toptim** [comment]
for clear syslog of course :)

**Comment by Grumpy-Dwarf** [comment]
`nocolor` option was added in [1.2.0 release](https://github.com/nanopool/nanominer/releases/tag/v1.2.0).
Just add `nocolor=true` somewhere at the beginning of your config.
