### ISSUE TITLE
Nanominer how transferring eth shares to my wallet

### ISSUE THREAD

**Issue by GeekoGeeko** [nanopool/nanominer#84]
So my nanominer is working fine and mining shares for me, only problem is that they are not showing up in my wallet. I have edited the config.ini and added my wallet address but still nothing. Please help when possible

**Comment by Grumpy-Dwarf** [comment]
You can see current income on pool account page. Payments are done during payout rounds once you've reached payout limit.

Anyway this issue is too old already. Hope everything is fine now.

**Comment by bhakuparkharsohtun** [comment]
You have to change the wallet address in this ini file also config_eth.
