### ISSUE TITLE
Nanominer 1.9.5 for windows is being flagged as a virus by Windows Defender 

### ISSUE THREAD

**Issue by mmmurf** [nanopool/nanominer#85]
1.9.4 is not being flagged.

**Comment by diegoly** [comment]
Same problem with me. Version 1.9.5 reported with virus and the previous version is clean.

**Comment by Shadowplays4k** [comment]
Trojan:Win32/Wacatac.D3!ml

in service.dll

version 1.13.0

Type: Trojan, Password stealing virus, Banking malware, Spyware

**Comment by crankfunk** [comment]
Mining software in general gets a lot of false positives from antivirus software to prevent crypto hijacking. Try uploading your service.dll at [virus total](https://www.virustotal.com/gui/) and see the results. If I upload mine there, it is marked as safe. Did you download your copy from a trusted source? However, actually it is possible, that you got some kind of virus. Make your decision on your own risk.

**Comment by kalxasath** [comment]
Something is very wrong with this version 3.3.5

results from virustotal.com

Ad-Aware	Gen:Variant.Razy.856062

AegisLab	Riskware.Win32.BitMiner.1!c

AhnLab-V3	Win-Trojan/Miner3.Exp

Alibaba	RiskWare:Win64/Miners.ad73c163

ALYac	Gen:Variant.Razy.856062

SecureAge APEX	Malicious

Avast	FileRepMalware [PUP]

AVG	FileRepMalware [PUP]

BitDefender	Gen:Variant.Razy.856062

CAT-QuickHeal	Trojan.CoinMiner

Cylance	Unsafe

Cyren	W64/Trojan.GCSI-1930

Emsisoft	Gen:Variant.Razy.856062 (B)

eScan	Gen:Variant.Razy.856062

ESET-NOD32	A Variant Of Win64/CoinMiner.MO Potentially Unwanted

FireEye	Generic.mg.c355dc4f6c32048c

Fortinet	Riskware/CoinMiner

GData	Gen:Variant.Razy.856062

Gridinsoft	Trojan.Heur!.02052023

K7AntiVirus	Adware ( 0053ced91 )

K7GW	Adware ( 0053ced91 )

Kaspersky	Not-a-virus:HEUR:RiskTool.Win32.BitMiner.gen

Malwarebytes	RiskWare.BitCoinMiner

MAX	Malware (ai Score=88)

MaxSecure	Trojan.Malware.12132254.susgen

McAfee	Artemis!C355DC4F6C32

McAfee-GW-Edition	Artemis

Microsoft	PUA:Win32/CoinMiner

Panda	Trj/CI.A

Rising	HackTool.CoinMiner!8.F154 (CLOUD)

Sophos	Generic PUA AN (PUA)

Symantec	PUA.Gen.2

TrendMicro	TROJ_GEN.R06BC0WE121

TrendMicro-HouseCall	TROJ_GEN.R06BC0WE121

VIPRE	Trojan.Win32.Generic!BT

Webroot	W32.Adware.Gen

Yandex	Riskware.Agent!ZXacole+KxQ

Zilly	Tool.BitMiner.Win32.1988
