### ISSUE TITLE
Nvidia GeForce GTX 960M not detected

### ISSUE THREAD

**Issue by valarmorghulis23** [nanopool/nanominer#87]
Hi, I'm having issues with nanominer running on my GPU instead of my CPU. When I start it up, it doesn't detect my graphics card and instead begins mining with my CPU (which has a considerably low hashrate when compared to my GPU). I've tried just about everything to get this to work but I'm at a loss. When I run a game, it runs using my graphics GPU, but nanominer goes straight for the CPU. Do you know what could be causing this and how I can fix the issue?

![miner](https://user-images.githubusercontent.com/68355455/87606573-4ebda900-c6c9-11ea-8f58-5fda707b88ef.jpg)

Attached you will find my clinfo for my graphics card.

[oclDeviceQuery.txt](https://github.com/nanopool/nanominer/files/4928301/oclDeviceQuery.txt)

Thanks in advance!

**Comment by valarmorghulis23** [comment]
Here's another screenshot that shows my graphics card being detected:

![detects](https://user-images.githubusercontent.com/68355455/87727418-70459000-c7b0-11ea-9aa6-d61922be1ef4.jpg)

**Comment by Grumpy-Dwarf** [comment]
XMR hash RandomX algorithm which is designed to be CPU-friendly and GPU-hard.
RandomX is only supported on CPU in nanominer.
