### ISSUE TITLE
can not connect to pools

### ISSUE THREAD

**Issue by talbotray** [nanopool/nanominer#95]
Startup info in log all looks ok,, but once it tries to connect to pools -- it can't. 

 Just get repeating messages that  "Connecting to pools ..."  followed by "Could not connect to any pools."  All the pools were added  and i can Ping them so there should be ok internet connectivity.  What needs to be checked and fixed?

**Comment by talbotray** [comment]
[log_2020-09-11_18-48-31.log](https://github.com/nanopool/nanominer/files/5212045/log_2020-09-11_18-48-31.log)

**Comment by red1412** [comment]
Bro， how you fix this problem？
