### ISSUE TITLE
Creates zombie processes when GPUs hang up

### ISSUE THREAD

**Issue by kendhitchcock** [nanopool/nanominer#96]
Currently i get occasional GPU hangups when tweaking my mining cards with CoreCtrl. This sends nanominer into restart mode but often ends up becoming a zombie process. The only course of action is to reboot.

What can i provide you next time it happens to better diagnose why the parent process (root) is not recognizing the child (nanominer) has died.

I am currently running on Ubuntu 20.04/8 cant remember off hand. 

Happy to help diagnose as much as possible and if i have the time i may look at the source code to see if i can find an answer too.

Kind regards
Ken

**Comment by Grumpy-Dwarf** [comment]
I'm afraid there are some kinds of hardware fails on AMD that leads to situation of any process freezes while accessing GPU. You can check if some harmless command like `clinfo` freezes next time nanominer becomes zombie.
If this is the case reboot is the only option I know. We have an `restarts` option which can be set to zero and `reboot.sh` script can perfrom sys-rq reboot.

**Comment by UselessGuru** [comment]
I see this frequently when overclocking too high.
