### ISSUE TITLE
AMD RX580 not detected by nanominer

### ISSUE THREAD

**Issue by Madeindreams** [nanopool/nanominer#97]
When running ./nanominer -d

```
Detected 1 device:
GPU 0  PCI 01:00.0  11170 MB  GeForce GTX 1080 Ti
```
I have 2 AMDRX580 as well.

when running lshw -c video

 ```
*-display                 
       description: VGA compatible controller
       product: GP102 [GeForce GTX 1080 Ti]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:152 memory:c1000000-c1ffffff memory:70000000-7fffffff memory:80000000-81ffffff ioport:5000(size=128) memory:c2000000-c207ffff
  *-display
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:04:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:150 memory:b0000000-bfffffff memory:c0000000-c01fffff ioport:4000(size=256) memory:c2400000-c243ffff memory:c2440000-c245ffff
  *-display
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:05:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:151 memory:90000000-9fffffff memory:a0000000-a01fffff ioport:3000(size=256) memory:c2300000-c233ffff memory:c2340000-c235ffff


```
How do I get nanominer to detect my AMD GPU

**Comment by Grumpy-Dwarf** [comment]
Do you have AMD `amdgpu-pro` Linux driver installed which supports OpenCL? If not, please use the following command during the installation for OpenCL support:
`./amdgpupro-install --headless --opencl=legacy,pal`.
On Ubuntu 20.04 it is also necessary to add current user to `render` group.

**Comment by Madeindreams** [comment]
Is there a way to clear the cache on these card? it says I have 80 mb free.

**Comment by IoT-master** [comment]
> Do you have AMD `amdgpu-pro` Linux driver installed which supports OpenCL? If not, please use the following command during the installation for OpenCL support:
> `./amdgpupro-install --headless --opencl=legacy,pal`.
> On Ubuntu 20.04 it is also necessary to add current user to `render` group.

Could you explain why is this now needed to get nanominer to now work?

**Comment by IoT-master** [comment]
`sudo usermod -a -G render $LOGNAME `
then logout to apply the changes.

**Comment by Grumpy-Dwarf** [comment]
> > Do you have AMD `amdgpu-pro` Linux driver installed which supports OpenCL? If not, please use the following command during the installation for OpenCL support:
> > `./amdgpupro-install --headless --opencl=legacy,pal`.
> > On Ubuntu 20.04 it is also necessary to add current user to `render` group.
> 
> Could you explain why is this now needed to get nanominer to now work?

This is a good question for AMD... I don't know what exactly fails without adding user to those group but OpenCL doesn't work without this.

**Comment by Grumpy-Dwarf** [comment]
> Is there a way to clear the cache on these card? it says I have 80 mb free.

What do you mean by clearing cache? If your drive storage is limited you can remove driver installation folder after install. The `amdgpu-pro-XXX.tar.xz` archive and the folder unpacked from it can be removed after installation.
