### ISSUE TITLE
Mining 0 Eth

### ISSUE THREAD

**Issue by ibmua** [nanopool/nanominer#98]
Card: RTX 3080
NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1

Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:00
Ethereum last 10 min - Total: 0.000 H/s.
2020-10-02 15:27:30: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:00
GPU0 t=51°C fan 0% power 111.79W. Total power: 111.79W
2020-10-02 15:27:33: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:03
2020-10-02 15:27:36: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:06
GPU0 t=53°C fan 50% power 151.91W. Total power: 151.91W
2020-10-02 15:27:39: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:10
Ethereum last 10 min - Total: 0.000 H/s.
2020-10-02 15:27:42: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:12
GPU0 t=53°C fan 59% power 150.63W. Total power: 150.63W
2020-10-02 15:27:45: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:15
2020-10-02 15:27:48: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:18
GPU0 t=52°C fan 59% power 150.89W. Total power: 150.89W
2020-10-02 15:27:51: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:21
Ethereum last 10 min - Total: 0.000 H/s.
2020-10-02 15:27:54: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:24
GPU0 t=52°C fan 59% power 148.97W. Total power: 148.97W
2020-10-02 15:27:57: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:27
2020-10-02 15:27:57: New job from eth-eu2.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:27
GPU0 t=51°C fan 59% power 149.52W. Total power: 149.52W

Power drawn, nothing gets mined. My card is one of those affected by a 2GHz bug, but it's probably not because of that, maybe because of newer CUDA version? I tried running in nvidia-docker for cuda 10.2, but in it nvidia-smi still said CUDA Version: 11.1, so I don't know if it maybe still didn't work just because CUDA was still v11.1.

Update 1: Does work with these versions on 2060 super, though. So the issue is only with 3080, maybe other Ampere cards.

Update 2: Also tried with 2080 ti and it works with 2080 ti

Version 1.11.0
2020-10-03 02:10:18: Started EthMan server on port 3333 without a password (read-only mode).
2020-10-03 02:10:18: Started web interface on port 9090 without a password.
2020-10-03 02:10:18: CUDA driver version is 11.1, runtime version is 10.0
Detected 2 devices
GPU 0 PCI 01:00.0, Platform: CUDA, Name: GeForce RTX 2080 Ti, 11018 MB available
GPU 1 PCI 03:00.0, Platform: CUDA, Name: GeForce RTX 3080, 10018 MB available
-------------------Ethash:------------------
Currency: ihor.ibm@gmail.com
Wallet: 0xf02d5583cac78083b84df1da12e478b8f9c2cb0b
Rig name: Garage
Email was not set.
Hashrate threshold to restart miner is not set
Added pool: eth-eu1.nanopool.org:9433
Added pool: eth-eu2.nanopool.org:9433
Added pool: eth-us-east1.nanopool.org:9433
Added pool: eth-us-west1.nanopool.org:9433
Added pool: eth-asia1.nanopool.org:9433
Added pool: eth-au1.nanopool.org:9433
Added pool: eth-jp1.nanopool.org:9433
Auto pool sorting is enabled
Using all GPU devices
Memory tweak: 1,1
-------------Common parameters:-------------
Log path: ./logs/
Log is written to file
GPU watchdog is enabled
Never calling reboot.sh (always restarting the miner in case of errors). 
2020-10-03 02:10:18: Setting up algorithm: Ethash
2020-10-03 02:10:19: Connecting to pools...
2020-10-03 02:10:19: Connected to pool: eth-eu1.nanopool.org:9433 | ping: 162 ms.
2020-10-03 02:10:19: New job from eth-eu1.nanopool.org:9433 | share difficulty = 10000 MH, epoch 365 (3943 MB)
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:00
Ethereum: GPU 0 0.000 H/s, GPU 1 0.000 H/s
GPU0 t=31°C fan 28% power 48.77W, GPU1 t=44°C fan 0% power 104.85W. Total power: 153.63W
2020-10-03 02:10:19: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:00
Ethereum: GPU 0 0.000 H/s, GPU 1 0.000 H/s
Ethereum last 10 min - GPU 0: 0.000 H/s, GPU 1: 0.000 H/s. Total: 0.000 H/s.
2020-10-03 02:10:20: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:01
Ethereum: GPU 0 0.000 H/s, GPU 1 0.000 H/s
GPU0 t=31°C fan 28% power 48.65W, GPU1 t=44°C fan 0% power 104.87W. Total power: 153.52W
2020-10-03 02:10:22: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:03
Ethereum: GPU 0 0.000 H/s, GPU 1 0.000 H/s
2020-10-03 02:10:23: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:04
Ethereum: GPU 0 0.000 H/s, GPU 1 0.000 H/s
GPU0 t=38°C fan 28% power 206.61W, GPU1 t=46°C fan 0% power 151.23W. Total power: 357.84W
2020-10-03 02:10:25: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 0.000 H/s, Total shares: 0 Rejected: 0, Time: 00:06
Ethereum: GPU 0 0.000 H/s, GPU 1 0.000 H/s
Ethereum last 10 min - GPU 0: 0.000 H/s, GPU 1: 0.000 H/s. Total: 0.000 H/s.
2020-10-03 02:10:26: GPU0: 3943 MB DAG generated in 4.65 seconds
2020-10-03 02:10:28: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 50.181 MH/s, Total shares: 0 Rejected: 0, Time: 00:09
Ethereum: GPU 0 50.181 MH/s, GPU 1 0.000 H/s
GPU0 t=42°C fan 30% power 217.39W, GPU1 t=48°C fan 0% power 152.56W. Total power: 369.95W
2020-10-03 02:10:31: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 50.222 MH/s, Total shares: 0 Rejected: 0, Time: 00:12
Ethereum: GPU 0 50.222 MH/s, GPU 1 0.000 H/s
2020-10-03 02:10:34: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 50.215 MH/s, Total shares: 0 Rejected: 0, Time: 00:15
Ethereum: GPU 0 50.215 MH/s, GPU 1 0.000 H/s
GPU0 t=46°C fan 31% power 220.03W, GPU1 t=49°C fan 0% power 154.75W. Total power: 374.78W
2020-10-03 02:10:37: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 50.222 MH/s, Total shares: 0 Rejected: 0, Time: 00:18
Ethereum: GPU 0 50.222 MH/s, GPU 1 0.000 H/s
Ethereum last 10 min - GPU 0: 50.213 MH/s, GPU 1: 0.000 H/s. Total: 50.213 MH/s.
2020-10-03 02:10:40: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 50.222 MH/s, Total shares: 0 Rejected: 0, Time: 00:21
Ethereum: GPU 0 50.222 MH/s, GPU 1 0.000 H/s
GPU0 t=49°C fan 32% power 227.06W, GPU1 t=50°C fan 0% power 157.15W. Total power: 384.21W
2020-10-03 02:10:43: New job from eth-eu1.nanopool.org:9433
Ethereum - Total speed: 50.218 MH/s, Total shares: 0 Rejected: 0, Time: 00:24
Ethereum: GPU 0 50.218 MH/s, GPU 1 0.000 H/s

**Comment by ibmua** [comment]
I thought maybe Claymore would work, but it doesn't work for any cards..

**Comment by ibmua** [comment]
If anybody else is dealing with this, use ethminer https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md + https://github.com/ethereum-mining/ethminer/issues/2027

**Comment by Grumpy-Dwarf** [comment]
Sorry, Ampere architecture is not yet supported in nanominer. We don't even have those GPUs for optimizing and testing yet. Will keep your updated.

**Comment by ibmua** [comment]
Optimizing will be harder, of course, but simply building is probably much easier. Ethminer was able to build with no code modifications, only added request for arch support during compilation.

**Comment by Grumpy-Dwarf** [comment]
We now support Nvidia Ampere 30xx GPUs in our 3.0+ `cuda11` version.
